//! `opportunities` data models for GoHighLevel API V2 (25 types).
//!
//! Generated from HighLevel's official OpenAPI spec for the
//! **Opportunities** module. Every endpoint that uses these types, with its
//! parameters, required scopes and enum values, is documented in the
//! [`opportunities` API reference](https://github.com/Shahroz/ghl-rs/blob/main/docs/api/opportunities.md).
//!
//! Enable with `features = ["opportunities"]`.
// @generated by xtask/generate_models.py — do not edit by hand.
// Source: https://github.com/GoHighLevel/highlevel-api-docs
// Doc comments are HighLevel's own field descriptions, reflowed verbatim, so
// they aren't held to rustdoc's markdown conventions.
#![allow(
    missing_docs,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items
)]

use serde::{Deserialize, Serialize};

/// `AdditionalDetailsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AdditionalDetailsDTO {
    /// Required by the API.
    pub notes: bool,
    /// Required by the API.
    pub tasks: bool,
    /// Required by the API.
    #[serde(rename = "calendarEvents")]
    pub calendar_events: bool,
    /// Required by the API.
    #[serde(rename = "unReadConversations")]
    pub un_read_conversations: bool,
}

/// `CreateAddFollowersSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateAddFollowersSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    #[serde(
        rename = "followersAdded",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub followers_added: Vec<String>,
}

/// `CreateDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateDto {
    /// pipeline Id
    /// Required by the API.
    #[serde(rename = "pipelineId")]
    pub pipeline_id: String,
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Required by the API.
    pub name: String,
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    /// Required by the API.
    pub status: String,
    /// Required by the API.
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<f64>,
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Add custom fields to opportunities.
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<serde_json::Value>,
}

/// `CustomFieldResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldResponseSchema {
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The value of the custom field
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<serde_json::Value>,
}

/// `DeleteFollowersSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteFollowersSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    #[serde(
        rename = "followersRemoved",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub followers_removed: Vec<String>,
}

/// `DeleteUpdateOpportunitySuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteUpdateOpportunitySuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
}

/// `FollowersDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FollowersDTO {
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
}

/// `GetPipelinesSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetPipelinesSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pipelines: Vec<PipelinesResponseSchema>,
}

/// `GetPostOpportunitySuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetPostOpportunitySuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opportunity: Option<SearchOpportunitiesResponseSchema>,
}

/// `LostReasonResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LostReasonResponseSchema {
    /// lost reason id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// lost reason name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// location id
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// updated at
    /// Format: date-time (ISO-8601 string).
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// created at
    /// Format: date-time (ISO-8601 string).
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

/// `LostReasonsResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LostReasonsResponseSchema {
    #[serde(rename = "lostReasons", default, skip_serializing_if = "Vec::is_empty")]
    pub lost_reasons: Vec<LostReasonResponseSchema>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
}

/// `OpportunitySearchBodyDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OpportunitySearchBodyDTO {
    /// Location Id
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Required by the API.
    pub query: String,
    /// Required by the API.
    pub limit: f64,
    /// Required by the API.
    pub page: f64,
    /// Required by the API.
    #[serde(rename = "searchAfter", default, skip_serializing_if = "Vec::is_empty")]
    pub search_after: Vec<String>,
    /// Required by the API.
    #[serde(rename = "additionalDetails")]
    pub additional_details: AdditionalDetailsDTO,
}

/// `PipelinesResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PipelinesResponseSchema {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub stages: Vec<Vec<serde_json::Value>>,
    #[serde(
        rename = "showInFunnel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub show_in_funnel: Option<bool>,
    #[serde(
        rename = "showInPieChart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub show_in_pie_chart: Option<bool>,
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// How pipeline/stage colors are rendered
    /// Allowed values: `dot`, `bg-tint`, `none`.
    #[serde(
        rename = "colorRenderMode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub color_render_mode: Option<String>,
}

/// `PostSearchSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostSearchSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub opportunities: Vec<SearchOpportunitiesResponseSchema>,
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aggregations: Option<serde_json::Value>,
}

/// `SearchMetaResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchMetaResponseSchema {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    #[serde(
        rename = "nextPageUrl",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_url: Option<String>,
    #[serde(
        rename = "startAfterId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start_after_id: Option<String>,
    #[serde(
        rename = "startAfter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start_after: Option<f64>,
    #[serde(
        rename = "currentPage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub current_page: Option<f64>,
    #[serde(rename = "nextPage", default, skip_serializing_if = "Option::is_none")]
    pub next_page: Option<f64>,
    #[serde(rename = "prevPage", default, skip_serializing_if = "Option::is_none")]
    pub prev_page: Option<f64>,
}

/// `SearchOpportunitiesContactResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchOpportunitiesContactResponseSchema {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "companyName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub company_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
}

/// `SearchOpportunitiesResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchOpportunitiesResponseSchema {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<f64>,
    #[serde(
        rename = "pipelineId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_id: Option<String>,
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(
        rename = "lastStatusChangeAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_status_change_at: Option<String>,
    #[serde(
        rename = "lastStageChangeAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_stage_change_at: Option<String>,
    #[serde(
        rename = "lastActionDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_action_date: Option<String>,
    #[serde(
        rename = "indexVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub index_version: Option<String>,
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "contactId", default, skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<SearchOpportunitiesContactResponseSchema>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub notes: Vec<Vec<serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tasks: Vec<Vec<serde_json::Value>>,
    #[serde(
        rename = "calendarEvents",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub calendar_events: Vec<Vec<serde_json::Value>>,
    #[serde(
        rename = "lostReasonId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lost_reason_id: Option<String>,
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<CustomFieldResponseSchema>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<Vec<serde_json::Value>>,
    #[serde(
        rename = "externalObjectId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub external_object_id: Option<String>,
}

/// `SearchSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub opportunities: Vec<SearchOpportunitiesResponseSchema>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<SearchMetaResponseSchema>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aggregations: Option<serde_json::Value>,
}

/// `UpdateOpportunityDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateOpportunityDto {
    /// pipeline Id
    #[serde(
        rename = "pipelineId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<f64>,
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Update custom fields to opportunities.
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<serde_json::Value>,
}

/// `UpdateStatusDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateStatusDto {
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    /// Required by the API.
    pub status: String,
    /// lost reason Id
    #[serde(
        rename = "lostReasonId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lost_reason_id: Option<String>,
}

/// `UpsertOpportunityDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpsertOpportunityDto {
    /// opportunityId
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// pipeline Id
    /// Required by the API.
    #[serde(rename = "pipelineId")]
    pub pipeline_id: String,
    /// locationId
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// contactId
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    /// isRemoveAllFollowers
    /// Required by the API.
    #[serde(rename = "isRemoveAllFollowers")]
    pub is_remove_all_followers: bool,
    /// followers action type
    /// Allowed values: `add`, `remove`.
    /// Required by the API.
    #[serde(rename = "followersActionType")]
    pub followers_action_type: String,
    /// name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<serde_json::Value>,
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// lost reason Id
    #[serde(
        rename = "lostReasonId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lost_reason_id: Option<String>,
}

/// `UpsertOpportunitySuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpsertOpportunitySuccessfulResponseDto {
    /// Updated / New Opportunity
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opportunity: Option<serde_json::Value>,
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub new: Option<bool>,
}

/// `customFieldsInputArraySchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputArraySchema {
    /// Required by the API.
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub field_value: Vec<String>,
}

/// `customFieldsInputObjectSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputObjectSchema {
    /// Required by the API.
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub field_value: Option<serde_json::Value>,
}

/// `customFieldsInputStringSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputStringSchema {
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub field_value: Option<String>,
}
