//! `users` data models for GoHighLevel API V2 (10 types).
//!
//! Generated from HighLevel's official OpenAPI spec for the
//! **Users** module. Every endpoint that uses these types, with its
//! parameters, required scopes and enum values, is documented in the
//! [`users` API reference](https://github.com/Shahroz/ghl-rs/blob/main/docs/api/users.md).
//!
//! Enable with `features = ["users"]`.
// @generated by xtask/generate_models.py — do not edit by hand.
// Source: https://github.com/GoHighLevel/highlevel-api-docs
// Doc comments are HighLevel's own field descriptions, reflowed verbatim, so
// they aren't held to rustdoc's markdown conventions.
#![allow(
    missing_docs,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items
)]

use serde::{Deserialize, Serialize};

/// `CreateUserDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateUserDto {
    /// Required by the API.
    #[serde(rename = "companyId")]
    pub company_id: String,
    /// Required by the API.
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// Required by the API.
    #[serde(rename = "lastName")]
    pub last_name: String,
    /// Required by the API.
    pub email: String,
    /// Required by the API.
    pub password: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Required by the API.
    #[serde(rename = "type")]
    pub type_: String,
    /// Required by the API.
    pub role: String,
    /// Required by the API.
    #[serde(rename = "locationIds", default, skip_serializing_if = "Vec::is_empty")]
    pub location_ids: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<PermissionsDto>,
    /// Scopes allowed for users. Only scopes that have been passed will be enabled. Note:- If
    /// passed empty all the scopes will be get disabled
    /// Allowed values: `campaigns.readonly`, `campaigns.write`, `calendars.readonly`,
    /// `calendars/events.write`, `calendars/groups.write`, `calendars.write`, `contacts.write`,
    /// `contacts/bulkActions.write`, `workflows.readonly`, `workflows.write`, `triggers.write`,
    /// `funnels.write`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub scopes: Vec<String>,
    /// Assigned Scopes allowed for users. Only scopes that have been passed will be enabled. If
    /// passed empty all the assigned scopes will be get disabled
    /// Allowed values: `campaigns.readonly`, `campaigns.write`, `calendars.readonly`,
    /// `calendars/events.write`, `calendars/groups.write`, `calendars.write`, `contacts.write`,
    /// `contacts/bulkActions.write`, `workflows.readonly`, `workflows.write`, `triggers.write`,
    /// `funnels.write`.
    #[serde(
        rename = "scopesAssignedToOnly",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub scopes_assigned_to_only: Vec<String>,
    #[serde(
        rename = "profilePhoto",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_photo: Option<String>,
    /// Per-location inbound Twilio number in E.164 format, keyed by location id (Call and
    /// Voicemail Inbound Number for direct Twilio, not LC Phone). Replacement semantics: if you
    /// send twilioPhone in the request body, the stored map is replaced entirely with this
    /// object (not merged). Any location id omitted from the object is removed from the saved
    /// map. Omit the twilioPhone property entirely to leave existing numbers unchanged. Send an
    /// empty object {} to clear all per-location numbers. To clear a single location only, set
    /// that location id to an empty string "".
    #[serde(
        rename = "twilioPhone",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub twilio_phone: Option<serde_json::Value>,
    /// Platform language preference for the user
    /// Allowed values: `en_US`, `es`, `fr_CA`, `fr_FR`, `nl`, `de`, `pt_PT`, `pt_BR`, `it`,
    /// `sv`, `da`, `fi`.
    #[serde(
        rename = "platformLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub platform_language: Option<String>,
}

/// `DeleteUserSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteUserSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// `FilterByEmailDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FilterByEmailDto {
    /// Company ID to filter users
    /// Required by the API.
    #[serde(rename = "companyId")]
    pub company_id: String,
    /// Comma-separated list of email addresses to filter users
    /// Required by the API.
    pub emails: String,
    /// Filter deleted users
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// No of results to be skipped before returning the result
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip: Option<String>,
    /// No of results to be limited before returning the result
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    /// Projection fields to return. Use "all" for all fields, or specify comma-separated field
    /// names. Default returns only id and email
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub projection: Option<String>,
}

/// `LocationSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LocationSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub users: Vec<UserSchema>,
}

/// `PermissionsDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PermissionsDto {
    #[serde(
        rename = "campaignsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub campaigns_enabled: Option<bool>,
    #[serde(
        rename = "campaignsReadOnly",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub campaigns_read_only: Option<bool>,
    #[serde(
        rename = "contactsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub contacts_enabled: Option<bool>,
    #[serde(
        rename = "workflowsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub workflows_enabled: Option<bool>,
    #[serde(
        rename = "workflowsReadOnly",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub workflows_read_only: Option<bool>,
    #[serde(
        rename = "triggersEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub triggers_enabled: Option<bool>,
    #[serde(
        rename = "funnelsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub funnels_enabled: Option<bool>,
    #[serde(
        rename = "websitesEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub websites_enabled: Option<bool>,
    #[serde(
        rename = "opportunitiesEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub opportunities_enabled: Option<bool>,
    #[serde(
        rename = "dashboardStatsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dashboard_stats_enabled: Option<bool>,
    #[serde(
        rename = "bulkRequestsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bulk_requests_enabled: Option<bool>,
    #[serde(
        rename = "appointmentsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub appointments_enabled: Option<bool>,
    #[serde(
        rename = "reviewsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reviews_enabled: Option<bool>,
    #[serde(
        rename = "onlineListingsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub online_listings_enabled: Option<bool>,
    #[serde(
        rename = "phoneCallEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_call_enabled: Option<bool>,
    #[serde(
        rename = "conversationsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub conversations_enabled: Option<bool>,
    #[serde(
        rename = "assignedDataOnly",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_data_only: Option<bool>,
    #[serde(
        rename = "adwordsReportingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub adwords_reporting_enabled: Option<bool>,
    #[serde(
        rename = "membershipEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub membership_enabled: Option<bool>,
    #[serde(
        rename = "facebookAdsReportingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub facebook_ads_reporting_enabled: Option<bool>,
    #[serde(
        rename = "attributionsReportingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attributions_reporting_enabled: Option<bool>,
    #[serde(
        rename = "settingsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub settings_enabled: Option<bool>,
    #[serde(
        rename = "tagsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tags_enabled: Option<bool>,
    #[serde(
        rename = "leadValueEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lead_value_enabled: Option<bool>,
    #[serde(
        rename = "marketingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub marketing_enabled: Option<bool>,
    #[serde(
        rename = "agentReportingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_reporting_enabled: Option<bool>,
    #[serde(
        rename = "botService",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_service: Option<bool>,
    #[serde(
        rename = "socialPlanner",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub social_planner: Option<bool>,
    #[serde(
        rename = "bloggingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub blogging_enabled: Option<bool>,
    #[serde(
        rename = "invoiceEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub invoice_enabled: Option<bool>,
    #[serde(
        rename = "affiliateManagerEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub affiliate_manager_enabled: Option<bool>,
    #[serde(
        rename = "contentAiEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub content_ai_enabled: Option<bool>,
    #[serde(
        rename = "refundsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_enabled: Option<bool>,
    #[serde(
        rename = "recordPaymentEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub record_payment_enabled: Option<bool>,
    #[serde(
        rename = "cancelSubscriptionEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub cancel_subscription_enabled: Option<bool>,
    #[serde(
        rename = "paymentsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub payments_enabled: Option<bool>,
    #[serde(
        rename = "communitiesEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub communities_enabled: Option<bool>,
    #[serde(
        rename = "exportPaymentsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub export_payments_enabled: Option<bool>,
}

/// `RoleSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RoleSchema {
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "locationIds", default, skip_serializing_if = "Vec::is_empty")]
    pub location_ids: Vec<String>,
    #[serde(
        rename = "restrictSubAccount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub restrict_sub_account: Option<bool>,
}

/// `SearchUserSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchUserSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub users: Vec<UserSchema>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<f64>,
}

/// `UpdateUserDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateUserDto {
    #[serde(rename = "firstName", default, skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", default, skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Email update is no longer supported due to security reasons.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Company/Agency Id. Required for Agency Level access
    #[serde(rename = "companyId", default, skip_serializing_if = "Option::is_none")]
    pub company_id: Option<String>,
    #[serde(rename = "locationIds", default, skip_serializing_if = "Vec::is_empty")]
    pub location_ids: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<PermissionsDto>,
    /// Scopes allowed for users. Only scopes that have been passed will be enabled. If passed
    /// empty all the scopes will be get disabled
    /// Allowed values: `campaigns.readonly`, `campaigns.write`, `calendars.readonly`,
    /// `calendars/events.write`, `calendars/groups.write`, `calendars.write`, `contacts.write`,
    /// `contacts/bulkActions.write`, `workflows.readonly`, `workflows.write`, `triggers.write`,
    /// `funnels.write`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub scopes: Vec<String>,
    /// Assigned Scopes allowed for users. Only scopes that have been passed will be enabled. If
    /// passed empty all the assigned scopes will be get disabled
    /// Allowed values: `campaigns.readonly`, `campaigns.write`, `calendars.readonly`,
    /// `calendars/events.write`, `calendars/groups.write`, `calendars.write`, `contacts.write`,
    /// `contacts/bulkActions.write`, `workflows.readonly`, `workflows.write`, `triggers.write`,
    /// `funnels.write`.
    #[serde(
        rename = "scopesAssignedToOnly",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub scopes_assigned_to_only: Vec<String>,
    #[serde(
        rename = "profilePhoto",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_photo: Option<String>,
    /// Per-location inbound Twilio number in E.164 format, keyed by location id (Call and
    /// Voicemail Inbound Number for direct Twilio, not LC Phone). Replacement semantics: if you
    /// send twilioPhone in the request body, the stored map is replaced entirely with this
    /// object (not merged). Any location id omitted from the object is removed from the saved
    /// map. Omit the twilioPhone property entirely to leave existing numbers unchanged. Send an
    /// empty object {} to clear all per-location numbers. To clear a single location only, set
    /// that location id to an empty string "".
    #[serde(
        rename = "twilioPhone",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub twilio_phone: Option<serde_json::Value>,
    /// Platform language preference for the user
    /// Allowed values: `en_US`, `es`, `fr_CA`, `fr_FR`, `nl`, `de`, `pt_PT`, `pt_BR`, `it`,
    /// `sv`, `da`, `fi`.
    #[serde(
        rename = "platformLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub platform_language: Option<String>,
}

/// `UserSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserSchema {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "firstName", default, skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", default, skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extension: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<PermissionsDto>,
    /// Allowed values: `campaigns.readonly`, `campaigns.write`, `calendars.readonly`,
    /// `calendars/events.write`, `calendars/groups.write`, `calendars.write`, `contacts.write`,
    /// `contacts/bulkActions.write`, `workflows.readonly`, `workflows.write`, `triggers.write`,
    /// `funnels.write`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scopes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub roles: Option<RoleSchema>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// LC Phone Inbound Phone Numbers
    #[serde(rename = "lcPhone", default, skip_serializing_if = "Option::is_none")]
    pub lc_phone: Option<serde_json::Value>,
    /// Platform language preference for the user
    /// Allowed values: `en_US`, `es`, `fr_CA`, `fr_FR`, `nl`, `de`, `pt_PT`, `pt_BR`, `it`,
    /// `sv`, `da`, `fi`.
    #[serde(
        rename = "platformLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub platform_language: Option<String>,
}

/// `UserSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserSuccessfulResponseDto {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "firstName", default, skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", default, skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extension: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<PermissionsDto>,
    /// Allowed values: `campaigns.readonly`, `campaigns.write`, `calendars.readonly`,
    /// `calendars/events.write`, `calendars/groups.write`, `calendars.write`, `contacts.write`,
    /// `contacts/bulkActions.write`, `workflows.readonly`, `workflows.write`, `triggers.write`,
    /// `funnels.write`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scopes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub roles: Option<RoleSchema>,
    /// LC Phone Inbound Phone Numbers
    #[serde(rename = "lcPhone", default, skip_serializing_if = "Option::is_none")]
    pub lc_phone: Option<serde_json::Value>,
    /// Platform language preference for the user
    /// Allowed values: `en_US`, `es`, `fr_CA`, `fr_FR`, `nl`, `de`, `pt_PT`, `pt_BR`, `it`,
    /// `sv`, `da`, `fi`.
    #[serde(
        rename = "platformLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub platform_language: Option<String>,
}
