//! `voice-ai` data models for GoHighLevel API V2 (35 types).
//!
//! Generated from HighLevel's official OpenAPI spec for the
//! **Voice Ai** module. Every endpoint that uses these types, with its
//! parameters, required scopes and enum values, is documented in the
//! [`voice-ai` API reference](https://github.com/Shahroz/ghl-rs/blob/main/docs/api/voice-ai.md).
//!
//! Enable with `features = ["voice-ai"]`.
// @generated by xtask/generate_models.py — do not edit by hand.
// Source: https://github.com/GoHighLevel/highlevel-api-docs
// Doc comments are HighLevel's own field descriptions, reflowed verbatim, so
// they aren't held to rustdoc's markdown conventions.
#![allow(
    missing_docs,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items
)]

use serde::{Deserialize, Serialize};

/// `AgentActionResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AgentActionResponseDTO {
    /// Unique identifier for this action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Type of action
    /// Allowed values: `CALL_TRANSFER`, `DATA_EXTRACTION`, `IN_CALL_DATA_EXTRACTION`,
    /// `WORKFLOW_TRIGGER`, `SMS`, `APPOINTMENT_BOOKING`, `CUSTOM_ACTION`, `KNOWLEDGE_BASE`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_type: Option<String>,
    /// Human-readable name for this action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Action parameters - structure varies by actionType
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionParameters",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_parameters: Option<serde_json::Value>,
}

/// `AgentCreationRequestDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AgentCreationRequestDTO {
    /// Unique identifier for the location where this agent will operate
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Display name for the voice AI agent, between 1-40 characters. Default: "My Agent {random
    /// 3 digit number}"
    #[serde(rename = "agentName", default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    /// Name of the business this agent represents. Default: Uses location name
    #[serde(
        rename = "businessName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub business_name: Option<String>,
    /// Initial greeting spoken when the agent answers calls. Default: Auto generated
    #[serde(
        rename = "welcomeMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub welcome_message: Option<String>,
    /// Custom instructions defining the agent's behavior and personality. Default: Basic prompt
    /// generated automatically
    #[serde(
        rename = "agentPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_prompt: Option<String>,
    /// Identifier for the speech synthesis voice from available voice options. Default: Auto
    /// generated
    #[serde(rename = "voiceId", default, skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<VoiceAILanguage>,
    #[serde(
        rename = "patienceLevel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub patience_level: Option<PatienceLevel>,
    /// Maximum call duration in seconds, between 180-900 (3-15 minutes). Default: 300 seconds
    /// (5 minutes)
    #[serde(
        rename = "maxCallDuration",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_call_duration: Option<f64>,
    /// Enables automatic reminders when callers are silent. Default: true
    #[serde(
        rename = "sendUserIdleReminders",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_user_idle_reminders: Option<bool>,
    /// Seconds to wait before sending idle reminders, between 1-20. Default: 8 seconds
    #[serde(
        rename = "reminderAfterIdleTimeSeconds",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reminder_after_idle_time_seconds: Option<f64>,
    /// Phone number for receiving inbound calls to this agent. Default: null
    #[serde(
        rename = "inboundNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_number: Option<String>,
    /// Identifier for the number pool managing phone number allocation. Default: null
    #[serde(
        rename = "numberPoolId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub number_pool_id: Option<String>,
    /// Array of workflow IDs to trigger automatically when calls end. Default: []
    #[serde(
        rename = "callEndWorkflowIds",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub call_end_workflow_ids: Vec<String>,
    /// Configuration for post-call email notifications to various recipients. Default: []
    #[serde(
        rename = "sendPostCallNotificationTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_post_call_notification_to: Option<SendPostCallNotificationDTO>,
    /// Time intervals defining when the agent accepts calls, organized by day of week. Default:
    /// [] (available 24/7)
    #[serde(
        rename = "agentWorkingHours",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub agent_working_hours: Vec<AgentWorkingHoursDTO>,
    /// IANA timezone identifier affecting working hours and scheduling. Default: Location
    /// timezone
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Prevents this agent from being used as a fallback option. Default: false (Available as
    /// backup agent)
    #[serde(
        rename = "isAgentAsBackupDisabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_agent_as_backup_disabled: Option<bool>,
    /// Language translation settings including enablement flag and target language code. Rules:
    /// (1) translation.enabled can only be true if the agent's language is not en-US; (2) when
    /// enabled, translation.language must be either the agent's language or en-US; (3) when
    /// enabled, translation.language is required.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub translation: Option<TranslationDTO>,
}

/// `AgentWorkingHoursDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AgentWorkingHoursDTO {
    /// Day of the week for this working hours configuration (Monday=1 to Sunday=7)
    /// Allowed values: `1`, `2`, `3`, `4`, `5`, `6`, `7`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "dayOfTheWeek",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub day_of_the_week: Option<String>,
    /// Array of time intervals when the agent is available on this day
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub intervals: Vec<IntervalDTO>,
}

/// `AppointmentBookingActionParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AppointmentBookingActionParameters {
    /// Calendar ID to book appointments in
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "calendarId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub calendar_id: Option<String>,
    /// Number of days ahead to offer booking dates
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "daysOfOfferingDates",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub days_of_offering_dates: Option<f64>,
    /// Number of available slots per day
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "slotsPerDay",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub slots_per_day: Option<f64>,
    /// Hours between available slots
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "hoursBetweenSlots",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub hours_between_slots: Option<f64>,
}

/// `CallActionSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallActionSchema {
    /// Action ID reference
    #[serde(rename = "actionId", default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<String>,
    /// Action type
    /// Allowed values: `CALL_TRANSFER`, `DATA_EXTRACTION`, `IN_CALL_DATA_EXTRACTION`,
    /// `WORKFLOW_TRIGGER`, `SMS`, `APPOINTMENT_BOOKING`, `CUSTOM_ACTION`, `KNOWLEDGE_BASE`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_type: Option<String>,
    /// Action name
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_name: Option<String>,
    /// Action parameters - structure varies by actionType
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "actionParameters",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_parameters: Option<serde_json::Value>,
    /// When the action was executed
    /// Format: date-time (ISO-8601 string).
    #[serde(
        rename = "executedAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub executed_at: Option<String>,
    /// When the trigger was received
    /// Format: date-time (ISO-8601 string).
    #[serde(
        rename = "triggerReceivedAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_received_at: Option<String>,
}

/// `CallLogDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallLogDTO {
    /// Unique identifier for the call
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Associated contact ID
    #[serde(rename = "contactId", default, skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
    /// Agent ID associated with the call
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "agentId", default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,
    /// Whether the agent is deleted
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "isAgentDeleted",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_agent_deleted: Option<bool>,
    /// Caller phone number
    #[serde(
        rename = "fromNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub from_number: Option<String>,
    /// Timestamp when the call was created
    /// Format: date-time (ISO-8601 string).
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Call duration in seconds
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    /// Whether this call was a trial call
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "trialCall", default, skip_serializing_if = "Option::is_none")]
    pub trial_call: Option<bool>,
    /// Actions performed during the call. Note: The APPOINTMENT_BOOKING action will only be
    /// visible in executedCallActions from Sep 9th 2025.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "executedCallActions",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub executed_call_actions: Vec<CallActionSchema>,
    /// Call summary
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// Call transcript
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transcript: Option<String>,
    /// Transcript translation details
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub translation: Option<TranslationSchema>,
    /// Dynamic data extracted from the call based on agent configuration
    #[serde(
        rename = "extractedData",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub extracted_data: Option<ExtractedDataSchema>,
    /// Message identifier associated with the call
    #[serde(rename = "messageId", default, skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
}

/// `CallLogsResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallLogsResponseDTO {
    /// Total number of items
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// Page number starting from 1
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page: Option<f64>,
    /// Number of items per page
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<f64>,
    /// Array of call logs
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "callLogs", default, skip_serializing_if = "Vec::is_empty")]
    pub call_logs: Vec<CallLogDTO>,
}

/// `CallTransferActionParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallTransferActionParameters {
    /// When to trigger this action during the call
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_prompt: Option<String>,
    /// Type of transfer destination (currently only "number" is supported)
    /// Allowed values: `number`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "transferToType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transfer_to_type: Option<String>,
    /// Phone number to transfer to. Must start with +, include country code, contain only
    /// numbers, and be 11-16 characters long (e.g., +12345678901).
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "transferToValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transfer_to_value: Option<String>,
    /// Message to tell the caller before transferring
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_message: Option<String>,
    /// Whether to play whisper message to the receiving party
    #[serde(
        rename = "hearWhisperMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub hear_whisper_message: Option<bool>,
}

/// `CreateActionResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateActionResponseDTO {
    /// Unique identifier for the created action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Type of action
    /// Allowed values: `CALL_TRANSFER`, `DATA_EXTRACTION`, `IN_CALL_DATA_EXTRACTION`,
    /// `WORKFLOW_TRIGGER`, `SMS`, `APPOINTMENT_BOOKING`, `CUSTOM_ACTION`, `KNOWLEDGE_BASE`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_type: Option<String>,
    /// Human-readable name for this action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Action parameters - structure varies by actionType
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionParameters",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_parameters: Option<serde_json::Value>,
}

/// `CreateAgentResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateAgentResponseDTO {
    /// Unique identifier for the created agent
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Unique identifier for the location where this agent operates
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Display name of the voice AI agent
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "agentName", default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    /// Name of the business this agent represents
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "businessName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub business_name: Option<String>,
    /// Greeting message spoken when the agent answers calls
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "welcomeMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub welcome_message: Option<String>,
    /// Custom instructions defining the agent's behavior
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "agentPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_prompt: Option<String>,
    /// Identifier for the speech synthesis voice being used
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "voiceId", default, skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    /// Language code for the agent's speech and understanding
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Current tolerance level for caller response delays
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "patienceLevel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub patience_level: Option<String>,
    /// Maximum call duration in seconds, between 180-900
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "maxCallDuration",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_call_duration: Option<f64>,
    /// Indicates whether automatic idle reminders are enabled
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "sendUserIdleReminders",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_user_idle_reminders: Option<bool>,
    /// Seconds to wait before sending idle reminders, between 1-20
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "reminderAfterIdleTimeSeconds",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reminder_after_idle_time_seconds: Option<f64>,
    /// Phone number for receiving inbound calls
    #[serde(
        rename = "inboundNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_number: Option<String>,
    /// Identifier for the number pool managing this agent's phone allocation
    #[serde(
        rename = "numberPoolId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub number_pool_id: Option<String>,
    /// Array of workflow IDs triggered automatically when calls end
    #[serde(
        rename = "callEndWorkflowIds",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub call_end_workflow_ids: Vec<String>,
    /// Current post-call notification settings including recipient configuration
    #[serde(
        rename = "sendPostCallNotificationTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_post_call_notification_to: Option<SendPostCallNotificationSchema>,
    /// Time intervals when the agent accepts calls, organized by day of week
    #[serde(
        rename = "agentWorkingHours",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub agent_working_hours: Vec<AgentWorkingHoursDTO>,
    /// IANA timezone identifier for working hours and scheduling
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Indicates whether this agent is excluded from backup scenarios
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "isAgentAsBackupDisabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_agent_as_backup_disabled: Option<bool>,
    /// Current language translation settings including enablement status and target language
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub translation: Option<TranslationSchema>,
}

/// `CreateSingleActionDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateSingleActionDTO {
    /// Agent ID to attach the action to
    /// Required by the API.
    #[serde(rename = "agentId")]
    pub agent_id: String,
    /// Location ID
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Type of action
    /// Allowed values: `CALL_TRANSFER`, `DATA_EXTRACTION`, `IN_CALL_DATA_EXTRACTION`,
    /// `WORKFLOW_TRIGGER`, `SMS`, `APPOINTMENT_BOOKING`, `CUSTOM_ACTION`, `KNOWLEDGE_BASE`.
    /// Required by the API.
    #[serde(rename = "actionType")]
    pub action_type: String,
    /// Human-readable name for this action
    /// Required by the API.
    pub name: String,
    /// Action parameters - structure varies by actionType
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    #[serde(rename = "actionParameters")]
    pub action_parameters: serde_json::Value,
}

/// `CustomActionApiDetailsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomActionApiDetailsDTO {
    /// API endpoint URL
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// HTTP method
    /// Allowed values: `POST`, `GET`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// Whether authentication is required
    #[serde(
        rename = "authenticationRequired",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub authentication_required: Option<bool>,
    /// Authentication token or API key (required if authenticationRequired is true)
    #[serde(
        rename = "authenticationValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub authentication_value: Option<String>,
    /// HTTP headers to include
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub headers: Vec<CustomActionHeaderDTO>,
    /// API parameters to send
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub parameters: Vec<CustomActionParameterDTO>,
}

/// `CustomActionHeaderDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomActionHeaderDTO {
    /// HTTP header name
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// HTTP header value
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// `CustomActionParameterDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomActionParameterDTO {
    /// Parameter name
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Parameter description
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Parameter type
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    /// Example parameter value
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub example: Option<String>,
}

/// `CustomActionParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomActionParameters {
    /// When to call the custom API
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_prompt: Option<String>,
    /// Message to tell the caller
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_message: Option<String>,
    /// API endpoint configuration
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "apiDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub api_details: Option<CustomActionApiDetailsDTO>,
    /// Selected response paths to extract from API response. Required: at least 1 value if the
    /// method is GET. Should be empty if the method is POST.
    #[serde(
        rename = "selectedPaths",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub selected_paths: Vec<String>,
}

/// `DataExtractionActionParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DataExtractionActionParameters {
    /// ID of the contact field to be updated with the extracted data
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "contactFieldId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub contact_field_id: Option<String>,
    /// Description of what data to extract
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Example values to help Agent understand the expected format. At least one example is
    /// required, maximum 5 examples allowed.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub examples: Vec<String>,
    /// Whether to overwrite existing field value if already set, default is false
    #[serde(
        rename = "overwriteExistingValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub overwrite_existing_value: Option<bool>,
}

/// `ExtractedDataSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ExtractedDataSchema {
    /// The spec defines no fields for this schema.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `GetActionResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetActionResponseDTO {
    /// Unique identifier for the action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Type of action
    /// Allowed values: `CALL_TRANSFER`, `DATA_EXTRACTION`, `IN_CALL_DATA_EXTRACTION`,
    /// `WORKFLOW_TRIGGER`, `SMS`, `APPOINTMENT_BOOKING`, `CUSTOM_ACTION`, `KNOWLEDGE_BASE`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_type: Option<String>,
    /// Human-readable name for this action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Action parameters - structure varies by actionType
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionParameters",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_parameters: Option<serde_json::Value>,
}

/// `GetAgentResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetAgentResponseDTO {
    /// Unique identifier for the created agent
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Unique identifier for the location where this agent operates
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Display name of the voice AI agent
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "agentName", default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    /// Name of the business this agent represents
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "businessName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub business_name: Option<String>,
    /// Greeting message spoken when the agent answers calls
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "welcomeMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub welcome_message: Option<String>,
    /// Custom instructions defining the agent's behavior
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "agentPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_prompt: Option<String>,
    /// Identifier for the speech synthesis voice being used
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "voiceId", default, skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    /// Language code for the agent's speech and understanding
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Current tolerance level for caller response delays
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "patienceLevel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub patience_level: Option<String>,
    /// Maximum call duration in seconds, between 180-900
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "maxCallDuration",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_call_duration: Option<f64>,
    /// Indicates whether automatic idle reminders are enabled
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "sendUserIdleReminders",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_user_idle_reminders: Option<bool>,
    /// Seconds to wait before sending idle reminders, between 1-20
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "reminderAfterIdleTimeSeconds",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reminder_after_idle_time_seconds: Option<f64>,
    /// Phone number for receiving inbound calls
    #[serde(
        rename = "inboundNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_number: Option<String>,
    /// Identifier for the number pool managing this agent's phone allocation
    #[serde(
        rename = "numberPoolId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub number_pool_id: Option<String>,
    /// Array of workflow IDs triggered automatically when calls end
    #[serde(
        rename = "callEndWorkflowIds",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub call_end_workflow_ids: Vec<String>,
    /// Current post-call notification settings including recipient configuration
    #[serde(
        rename = "sendPostCallNotificationTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_post_call_notification_to: Option<SendPostCallNotificationSchema>,
    /// Time intervals when the agent accepts calls, organized by day of week
    #[serde(
        rename = "agentWorkingHours",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub agent_working_hours: Vec<AgentWorkingHoursDTO>,
    /// IANA timezone identifier for working hours and scheduling
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Indicates whether this agent is excluded from backup scenarios
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "isAgentAsBackupDisabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_agent_as_backup_disabled: Option<bool>,
    /// Current language translation settings including enablement status and target language
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub translation: Option<TranslationSchema>,
    /// Raw actions configured for this agent with complete actionParameters structure
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub actions: Vec<AgentActionResponseDTO>,
}

/// `GetAgentsResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetAgentsResponseDTO {
    /// Total number of items
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// Page number starting from 1
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page: Option<f64>,
    /// Number of items per page
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<f64>,
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub agents: Vec<GetAgentResponseDTO>,
}

/// `InCallDataExtractionActionParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InCallDataExtractionActionParameters {
    /// ID of the contact field to be updated with the extracted data
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "contactFieldId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub contact_field_id: Option<String>,
    /// Description of what data to extract
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Example values to help Agent understand the expected format. At least one example is
    /// required, maximum 5 examples allowed.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub examples: Vec<String>,
    /// Whether to overwrite existing field value if already set, default is false
    #[serde(
        rename = "overwriteExistingValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub overwrite_existing_value: Option<bool>,
}

/// `IntervalDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IntervalDTO {
    /// Starting hour of the working interval in 24-hour format (0-23)
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "startHour", default, skip_serializing_if = "Option::is_none")]
    pub start_hour: Option<f64>,
    /// Ending hour of the working interval in 24-hour format (0-23)
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "endHour", default, skip_serializing_if = "Option::is_none")]
    pub end_hour: Option<f64>,
    /// Starting minute of the working interval (0-59)
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "startMinute",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start_minute: Option<f64>,
    /// Ending minute of the working interval (0-59)
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "endMinute", default, skip_serializing_if = "Option::is_none")]
    pub end_minute: Option<f64>,
}

/// `KnowledgeBaseParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct KnowledgeBaseParameters {
    /// When to query the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_prompt: Option<String>,
    /// Knowledge base ID to query
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "knowledgeBaseId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_base_id: Option<String>,
}

/// `PatchAgentDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PatchAgentDTO {
    /// Display name for the voice AI agent, between 1-40 characters. Default: "My Agent {random
    /// 3 digit number}"
    #[serde(rename = "agentName", default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    /// Name of the business this agent represents. Default: Uses location name
    #[serde(
        rename = "businessName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub business_name: Option<String>,
    /// Initial greeting spoken when the agent answers calls. Default: Auto generated
    #[serde(
        rename = "welcomeMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub welcome_message: Option<String>,
    /// Custom instructions defining the agent's behavior and personality. Default: Basic prompt
    /// generated automatically
    #[serde(
        rename = "agentPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_prompt: Option<String>,
    /// Identifier for the speech synthesis voice from available voice options. Default: Auto
    /// generated
    #[serde(rename = "voiceId", default, skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<VoiceAILanguage>,
    #[serde(
        rename = "patienceLevel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub patience_level: Option<PatienceLevel>,
    /// Maximum call duration in seconds, between 180-900 (3-15 minutes). Default: 300 seconds
    /// (5 minutes)
    #[serde(
        rename = "maxCallDuration",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_call_duration: Option<f64>,
    /// Enables automatic reminders when callers are silent. Default: true
    #[serde(
        rename = "sendUserIdleReminders",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_user_idle_reminders: Option<bool>,
    /// Seconds to wait before sending idle reminders, between 1-20. Default: 8 seconds
    #[serde(
        rename = "reminderAfterIdleTimeSeconds",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reminder_after_idle_time_seconds: Option<f64>,
    /// Phone number for receiving inbound calls to this agent. Default: null
    #[serde(
        rename = "inboundNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_number: Option<String>,
    /// Identifier for the number pool managing phone number allocation. Default: null
    #[serde(
        rename = "numberPoolId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub number_pool_id: Option<String>,
    /// Array of workflow IDs to trigger automatically when calls end. Default: []
    #[serde(
        rename = "callEndWorkflowIds",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub call_end_workflow_ids: Vec<String>,
    /// Configuration for post-call email notifications to various recipients. Default: []
    #[serde(
        rename = "sendPostCallNotificationTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_post_call_notification_to: Option<SendPostCallNotificationDTO>,
    /// Time intervals defining when the agent accepts calls, organized by day of week. Default:
    /// [] (available 24/7)
    #[serde(
        rename = "agentWorkingHours",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub agent_working_hours: Vec<AgentWorkingHoursDTO>,
    /// IANA timezone identifier affecting working hours and scheduling. Default: Location
    /// timezone
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Prevents this agent from being used as a fallback option. Default: false (Available as
    /// backup agent)
    #[serde(
        rename = "isAgentAsBackupDisabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_agent_as_backup_disabled: Option<bool>,
    /// Language translation settings including enablement flag and target language code. Rules:
    /// (1) translation.enabled can only be true if the agent's language is not en-US; (2) when
    /// enabled, translation.language must be either the agent's language or en-US; (3) when
    /// enabled, translation.language is required.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub translation: Option<TranslationDTO>,
}

/// `PatchAgentResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PatchAgentResponseDTO {
    /// Unique identifier for the created agent
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Unique identifier for the location where this agent operates
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Display name of the voice AI agent
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "agentName", default, skip_serializing_if = "Option::is_none")]
    pub agent_name: Option<String>,
    /// Name of the business this agent represents
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "businessName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub business_name: Option<String>,
    /// Greeting message spoken when the agent answers calls
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "welcomeMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub welcome_message: Option<String>,
    /// Custom instructions defining the agent's behavior
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "agentPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_prompt: Option<String>,
    /// Identifier for the speech synthesis voice being used
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "voiceId", default, skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    /// Language code for the agent's speech and understanding
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Current tolerance level for caller response delays
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "patienceLevel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub patience_level: Option<String>,
    /// Maximum call duration in seconds, between 180-900
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "maxCallDuration",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_call_duration: Option<f64>,
    /// Indicates whether automatic idle reminders are enabled
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "sendUserIdleReminders",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_user_idle_reminders: Option<bool>,
    /// Seconds to wait before sending idle reminders, between 1-20
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "reminderAfterIdleTimeSeconds",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reminder_after_idle_time_seconds: Option<f64>,
    /// Phone number for receiving inbound calls
    #[serde(
        rename = "inboundNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_number: Option<String>,
    /// Identifier for the number pool managing this agent's phone allocation
    #[serde(
        rename = "numberPoolId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub number_pool_id: Option<String>,
    /// Array of workflow IDs triggered automatically when calls end
    #[serde(
        rename = "callEndWorkflowIds",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub call_end_workflow_ids: Vec<String>,
    /// Current post-call notification settings including recipient configuration
    #[serde(
        rename = "sendPostCallNotificationTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub send_post_call_notification_to: Option<SendPostCallNotificationSchema>,
    /// Time intervals when the agent accepts calls, organized by day of week
    #[serde(
        rename = "agentWorkingHours",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub agent_working_hours: Vec<AgentWorkingHoursDTO>,
    /// IANA timezone identifier for working hours and scheduling
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Indicates whether this agent is excluded from backup scenarios
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "isAgentAsBackupDisabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_agent_as_backup_disabled: Option<bool>,
    /// Current language translation settings including enablement status and target language
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub translation: Option<TranslationSchema>,
}

/// Tolerance level for caller response delays. Default: "high"
/// Allowed values: `low`, `medium`, `high`.
/// Kept as `String` so new upstream values don't break deserialization.
pub type PatienceLevel = String;

/// `SMSParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SMSParameters {
    /// When to send the SMS
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_prompt: Option<String>,
    /// Message to tell the caller
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_message: Option<String>,
    /// SMS message content to send
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "messageBody",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub message_body: Option<String>,
}

/// `SendPostCallNotificationDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SendPostCallNotificationDTO {
    /// Enables post-call notifications to all admin users in the location. Default: true
    /// Required by the API.
    pub admins: bool,
    /// Enables post-call notifications to all users in the location. Default: false
    /// Required by the API.
    #[serde(rename = "allUsers")]
    pub all_users: bool,
    /// Enables post-call notifications to the user assigned to the contact. Default: false
    /// Required by the API.
    #[serde(rename = "contactAssignedUser")]
    pub contact_assigned_user: bool,
    /// Array of specific user IDs to receive post-call notifications. Default: []
    /// Required by the API.
    #[serde(
        rename = "specificUsers",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub specific_users: Vec<String>,
    /// Array of custom email addresses to receive post-call notifications. Default: []
    /// Required by the API.
    #[serde(
        rename = "customEmails",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_emails: Vec<String>,
}

/// `SendPostCallNotificationSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SendPostCallNotificationSchema {
    /// Send notifications to admins
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub admins: Option<bool>,
    /// Send notifications to all users
    #[serde(rename = "allUsers", default, skip_serializing_if = "Option::is_none")]
    pub all_users: Option<bool>,
    /// Send notifications to contact assigned user
    #[serde(
        rename = "contactAssignedUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub contact_assigned_user: Option<bool>,
    /// Specific user IDs to notify
    #[serde(
        rename = "specificUsers",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub specific_users: Vec<String>,
    /// Custom email addresses to notify
    #[serde(
        rename = "customEmails",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_emails: Vec<String>,
}

/// `TranslationDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TranslationDTO {
    /// Enables language translation for agent conversations. Default: false
    /// Required by the API.
    pub enabled: bool,
    /// Target language code for translation (e.g., "es" for Spanish, "fr" for French).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

/// `TranslationSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TranslationSchema {
    /// Whether translation is enabled
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Translation language code
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

/// `UpdateActionResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateActionResponseDTO {
    /// Unique identifier for the created action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Type of action
    /// Allowed values: `CALL_TRANSFER`, `DATA_EXTRACTION`, `IN_CALL_DATA_EXTRACTION`,
    /// `WORKFLOW_TRIGGER`, `SMS`, `APPOINTMENT_BOOKING`, `CUSTOM_ACTION`, `KNOWLEDGE_BASE`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_type: Option<String>,
    /// Human-readable name for this action
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Action parameters - structure varies by actionType
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "actionParameters",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_parameters: Option<serde_json::Value>,
}

/// `UpdateSingleActionDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateSingleActionDTO {
    /// Agent ID to attach the action to
    /// Required by the API.
    #[serde(rename = "agentId")]
    pub agent_id: String,
    /// Location ID
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Type of action
    /// Allowed values: `CALL_TRANSFER`, `DATA_EXTRACTION`, `IN_CALL_DATA_EXTRACTION`,
    /// `WORKFLOW_TRIGGER`, `SMS`, `APPOINTMENT_BOOKING`, `CUSTOM_ACTION`, `KNOWLEDGE_BASE`.
    /// Required by the API.
    #[serde(rename = "actionType")]
    pub action_type: String,
    /// Human-readable name for this action
    /// Required by the API.
    pub name: String,
    /// Action parameters - structure varies by actionType
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    #[serde(rename = "actionParameters")]
    pub action_parameters: serde_json::Value,
}

/// Language code for the agent's speech and understanding. Default: "en-US"
/// Allowed values: `en-US`, `pt-BR`, `es`, `fr`, `de`, `it`, `nl-NL`, `multi`.
/// Kept as `String` so new upstream values don't break deserialization.
pub type VoiceAILanguage = String;

/// `WorkflowTriggerParameters` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WorkflowTriggerParameters {
    /// When to trigger this workflow
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerPrompt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_prompt: Option<String>,
    /// Message to tell the caller
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "triggerMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_message: Option<String>,
    /// Workflow ID to trigger
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "workflowId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub workflow_id: Option<String>,
}
