//! `contacts` data models for GoHighLevel API V3 (60 types).
//!
//! Generated from HighLevel's official OpenAPI spec for the
//! **Contacts** module. Every endpoint that uses these types, with its
//! parameters, required scopes and enum values, is documented in the
//! [`contacts` API reference](https://github.com/Shahroz/ghl-rs/blob/main/docs/api/contacts.md).
//!
//! Enable with `features = ["contacts"]`.
// @generated by xtask/generate_models.py — do not edit by hand.
// Source: https://github.com/GoHighLevel/highlevel-api-docs
// Doc comments are HighLevel's own field descriptions, reflowed verbatim, so
// they aren't held to rustdoc's markdown conventions.
#![allow(
    missing_docs,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items
)]

use serde::{Deserialize, Serialize};

/// `AddContactToCampaignDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AddContactToCampaignDto {
    /// The spec defines no fields for this schema.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `AttributionSource` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AttributionSource {
    /// Attribution source type
    /// Required by the API.
    pub url: String,
    /// Campaign name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub campaign: Option<String>,
    /// UTM source parameter
    #[serde(rename = "utmSource", default, skip_serializing_if = "Option::is_none")]
    pub utm_source: Option<String>,
    /// UTM medium parameter
    #[serde(rename = "utmMedium", default, skip_serializing_if = "Option::is_none")]
    pub utm_medium: Option<String>,
    /// UTM content parameter
    #[serde(
        rename = "utmContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub utm_content: Option<String>,
    /// Referrer URL
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub referrer: Option<String>,
    /// Campaign Id
    #[serde(
        rename = "campaignId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub campaign_id: Option<String>,
    /// Facebook click Id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fbclid: Option<String>,
    /// Google click Id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gclid: Option<String>,
    /// Microsoft click Id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub msclikid: Option<String>,
    /// DoubleClick click Id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dclid: Option<String>,
    /// Facebook browser Id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fbc: Option<String>,
    /// Facebook pixel Id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fbp: Option<String>,
    /// Facebook event Id
    #[serde(rename = "fbEventId", default, skip_serializing_if = "Option::is_none")]
    pub fb_event_id: Option<String>,
    /// Browser user agent string
    #[serde(rename = "userAgent", default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    /// IP address of the visitor
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    /// Attribution medium (e.g. survey, funnel)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub medium: Option<String>,
    /// Id of the attribution medium
    #[serde(rename = "mediumId", default, skip_serializing_if = "Option::is_none")]
    pub medium_id: Option<String>,
}

/// `CheckboxField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CheckboxField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Array of selected checkbox values for the custom field (preferred).
    #[serde(rename = "fieldValue", default, skip_serializing_if = "Vec::is_empty")]
    pub field_value: Vec<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(rename = "field_value", default, skip_serializing_if = "Vec::is_empty")]
    pub field_value_alt: Vec<String>,
}

/// `ContactsBulkUpateResponse` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContactsBulkUpateResponse {
    /// Whether the bulk update was successful
    /// Required by the API.
    pub success: bool,
    /// List of contact Ids that were updated
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ids: Vec<String>,
}

/// `ContactsBusinessUpdate` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContactsBusinessUpdate {
    /// Location Id
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// List of contact Ids to update (maximum 50)
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ids: Vec<String>,
    /// Business Id to assign to contacts. Pass null to remove business association.
    /// Required by the API.
    #[serde(rename = "businessId")]
    pub business_id: String,
}

/// `ContactsByIdSuccessfulResponseDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContactsByIdSuccessfulResponseDtoV3 {
    /// Contact details
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<GetContactByIdSchemaV3>,
}

/// `ContactsMetaSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContactsMetaSchema {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    #[serde(
        rename = "nextPageUrl",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_url: Option<String>,
    #[serde(
        rename = "startAfterId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start_after_id: Option<String>,
    #[serde(
        rename = "startAfter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start_after: Option<f64>,
    #[serde(
        rename = "currentPage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub current_page: Option<f64>,
    #[serde(rename = "nextPage", default, skip_serializing_if = "Option::is_none")]
    pub next_page: Option<f64>,
    #[serde(rename = "prevPage", default, skip_serializing_if = "Option::is_none")]
    pub prev_page: Option<f64>,
}

/// `ContactsSearchSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContactsSearchSchema {
    /// Unique identifier of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Location Id the contact belongs to
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Email address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Timezone of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Country of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Source from which the contact was created
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Date and time the contact was added (ISO 8601)
    #[serde(rename = "dateAdded", default, skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    /// List of custom field values for the contact
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<CustomFieldSchema>,
    /// List of tags associated with the contact
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// Business Id the contact is associated with
    #[serde(
        rename = "businessId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub business_id: Option<String>,
    /// List of attribution sources for the contact
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub attributions: Vec<AttributionSource>,
    /// List of user Ids following this contact
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
}

/// `ContactsSearchSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContactsSearchSuccessfulResponseDto {
    /// List of contacts associated with the business
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub contacts: Vec<ContactsSearchSchema>,
    /// Total number of contacts matching the query
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<f64>,
}

/// `ContactsWorkflowSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContactsWorkflowSuccessfulResponseDto {
    /// Whether the workflow operation was successful
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<bool>,
    /// Legacy misspelling of `succeeded`. Deprecated; use `succeeded`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
}

/// `CreateAddFollowersSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateAddFollowersSuccessfulResponseDto {
    /// Current followers after the operation
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    /// Followers that were added
    #[serde(
        rename = "followersAdded",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub followers_added: Vec<String>,
}

/// `CreateAddTagSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateAddTagSuccessfulResponseDto {
    /// Current tags on the contact after the operation
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
}

/// `CreateContactDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateContactDtoV3 {
    /// First name of the contact
    #[serde(rename = "firstName", default, skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name of the contact
    #[serde(rename = "lastName", default, skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Full name of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Email address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Location Id the contact should be created under
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Gender of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    /// Phone number of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Street address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address1: Option<String>,
    /// City of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// State of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Postal code of the contact
    #[serde(
        rename = "postalCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    /// Website URL of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// Timezone of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Whether Do Not Disturb is enabled for the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dnd: Option<bool>,
    /// Inbound DND settings per channel for the contact
    #[serde(
        rename = "inboundDndSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_dnd_settings: Option<InboundDndSettingsSchema>,
    /// List of tags to assign to the contact
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// List of custom field values to assign to the contact
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<serde_json::Value>,
    /// Source from which the contact was created
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// The birth date of the contact. Supported formats: YYYY/MM/DD, MM/DD/YYYY, YYYY-MM-DD,
    /// MM-DD-YYYY, YYYY.MM.DD, MM.DD.YYYY, YYYY_MM_DD, MM_DD_YYYY
    #[serde(
        rename = "dateOfBirth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub date_of_birth: Option<serde_json::Value>,
    /// Country code of the contact (ISO 3166-1 alpha-2)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Company name of the contact
    #[serde(
        rename = "companyName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub company_name: Option<String>,
    /// User's Id
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Per-channel DND settings for the contact
    #[serde(
        rename = "dndSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dnd_settings: Option<DndSettingsSchemaV3>,
}

/// `CreateContactsSuccessfulResponseDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateContactsSuccessfulResponseDtoV3 {
    /// Contact details
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<GetContactByIdSchemaV3>,
}

/// `CreateDeleteCantactsCampaignsSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateDeleteCantactsCampaignsSuccessfulResponseDto {
    /// Whether the campaign operation was successful
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<bool>,
    /// Legacy misspelling of `succeeded`. Deprecated; use `succeeded`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
}

/// `CreateDeleteTagSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateDeleteTagSuccessfulResponseDto {
    /// Current tags on the contact after the operation
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
}

/// `CreateTaskParams` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateTaskParams {
    /// Title of the task
    /// Required by the API.
    pub title: String,
    /// Body or description of the task
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// Due date of the task (ISO 8601 format)
    /// Required by the API.
    #[serde(rename = "dueDate")]
    pub due_date: String,
    /// Whether the task is completed
    /// Required by the API.
    pub completed: bool,
    /// User Id to whom the task is assigned
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
}

/// `CreateWorkflowDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateWorkflowDto {
    /// Start time of the workflow event (ISO 8601 format)
    #[serde(
        rename = "eventStartTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub event_start_time: Option<String>,
}

/// `CustomFieldSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldSchema {
    /// Unique identifier of the custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Value of the custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// `DeleteContactsSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteContactsSuccessfulResponseDto {
    /// Whether the delete operation succeeded
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<bool>,
    /// Legacy misspelling of `succeeded`. Deprecated; use `succeeded`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
}

/// `DeleteFollowersSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteFollowersSuccessfulResponseDto {
    /// Current followers after the operation
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    /// Followers that were removed
    #[serde(
        rename = "followersRemoved",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub followers_removed: Vec<String>,
}

/// `DeleteNoteSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteNoteSuccessfulResponseDto {
    /// Whether the note was successfully deleted
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<bool>,
    /// Legacy misspelling of `succeeded`. Deprecated; use `succeeded`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
}

/// `DeleteTaskSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteTaskSuccessfulResponseDto {
    /// Whether the task was successfully deleted
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<bool>,
    /// Legacy misspelling of `succeeded`. Deprecated; use `succeeded`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
}

/// `DndSettingSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DndSettingSchema {
    /// Do Not Disturb status for this channel
    /// Allowed values: `active`, `inactive`, `permanent`.
    /// Required by the API.
    pub status: String,
    /// Custom message associated with the DND setting
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// DND code or reason
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

/// `DndSettingsSchemaV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DndSettingsSchemaV3 {
    /// DND settings for phone calls
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call: Option<DndSettingSchema>,
    /// DND settings for email
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<DndSettingSchema>,
    /// DND settings for SMS
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sms: Option<DndSettingSchema>,
    /// DND settings for WhatsApp
    #[serde(rename = "whatsApp", default, skip_serializing_if = "Option::is_none")]
    pub whats_app: Option<DndSettingSchema>,
    /// DND settings for Google My Business
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gmb: Option<DndSettingSchema>,
    /// DND settings for Facebook
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fb: Option<DndSettingSchema>,
}

/// `FileField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FileField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// File upload value — a map of UUID to file metadata and download URL (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<serde_json::Value>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<serde_json::Value>,
}

/// `FollowersDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FollowersDTO {
    /// List of user Ids to follow or unfollow the contact
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
}

/// `GetContactByIdSchemaV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetContactByIdSchemaV3 {
    /// Unique identifier of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Full name of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Location Id the contact belongs to
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// First name of the contact
    #[serde(rename = "firstName", default, skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name of the contact
    #[serde(rename = "lastName", default, skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Email address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Lowercase version of the contact email
    #[serde(
        rename = "emailLowerCase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub email_lower_case: Option<String>,
    /// Timezone of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Company name of the contact
    #[serde(
        rename = "companyName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub company_name: Option<String>,
    /// Phone number of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Whether Do Not Disturb is enabled for the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dnd: Option<bool>,
    /// Contact type classification
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    /// Source from which the contact was created
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// User Id the contact is assigned to
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Street address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address1: Option<String>,
    /// City of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// State of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Country of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Postal code of the contact
    #[serde(
        rename = "postalCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    /// Website URL of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// List of tags associated with the contact
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// Date of birth of the contact (YYYY-MM-DD)
    #[serde(
        rename = "dateOfBirth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub date_of_birth: Option<String>,
    /// Date and time the contact was added (ISO 8601)
    #[serde(rename = "dateAdded", default, skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    /// Date and time the contact was last updated (ISO 8601)
    #[serde(
        rename = "dateUpdated",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<String>,
    /// List of attachment URLs associated with the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attachments: Option<String>,
    /// Social Security Number (if applicable)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssn: Option<String>,
    /// Search keyword associated with the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keyword: Option<String>,
    /// Lowercase version of the contact first name
    #[serde(
        rename = "firstNameLowerCase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name_lower_case: Option<String>,
    /// Lowercase version of the contact full name
    #[serde(
        rename = "fullNameLowerCase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub full_name_lower_case: Option<String>,
    /// Lowercase version of the contact last name
    #[serde(
        rename = "lastNameLowerCase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name_lower_case: Option<String>,
    /// Date and time of last activity on this contact (ISO 8601)
    #[serde(
        rename = "lastActivity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_activity: Option<String>,
    /// List of custom field values for the contact
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<CustomFieldSchema>,
    /// Business Id the contact is associated with
    #[serde(
        rename = "businessId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub business_id: Option<String>,
    /// First-touch attribution source details for the contact
    #[serde(
        rename = "attributionSource",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attribution_source: Option<AttributionSource>,
    /// Last-touch attribution source details for the contact
    #[serde(
        rename = "lastAttributionSource",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_attribution_source: Option<AttributionSource>,
    /// visitorId is the Unique ID assigned to each Live chat visitor.
    #[serde(rename = "visitorId", default, skip_serializing_if = "Option::is_none")]
    pub visitor_id: Option<String>,
    /// Per-channel DND settings for the contact
    #[serde(
        rename = "dndSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dnd_settings: Option<DndSettingsSchemaV3>,
}

/// `GetCreateUpdateNoteSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetCreateUpdateNoteSuccessfulResponseDto {
    /// Note details
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<GetNoteSchema>,
}

/// `GetEventSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetEventSchema {
    /// Unique identifier of the appointment
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Calendar Id associated with the appointment
    #[serde(
        rename = "calendarId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub calendar_id: Option<String>,
    /// Status of the appointment
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Title of the appointment
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// User Id assigned to the appointment
    #[serde(
        rename = "assignedUserId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_user_id: Option<String>,
    /// Notes for the appointment
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Start time of the appointment
    #[serde(rename = "startTime", default, skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    /// End time of the appointment
    #[serde(rename = "endTime", default, skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    /// Address for the appointment
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Location Id of the appointment
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Contact Id associated with the appointment
    #[serde(rename = "contactId", default, skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
    /// Group Id of the appointment
    #[serde(rename = "groupId", default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    /// Appointment status
    #[serde(
        rename = "appointmentStatus",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub appointment_status: Option<String>,
    /// List of user Ids assigned to the appointment
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub users: Vec<String>,
    /// Date the appointment was created
    #[serde(rename = "dateAdded", default, skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    /// Date the appointment was last updated
    #[serde(
        rename = "dateUpdated",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<String>,
    /// List of resource Ids assigned to the appointment
    #[serde(
        rename = "assignedResources",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub assigned_resources: Vec<String>,
}

/// `GetEventsSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetEventsSuccessfulResponseDto {
    /// List of appointments
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub events: Vec<GetEventSchema>,
}

/// `GetNoteSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetNoteSchema {
    /// Unique identifier of the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Body content of the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// User Id of the note author
    #[serde(rename = "userId", default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Date the note was added (ISO 8601 format)
    #[serde(rename = "dateAdded", default, skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    /// Contact Id associated with the note
    #[serde(rename = "contactId", default, skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
    /// Title of the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Hex color code for the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Whether the note is pinned
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pinned: Option<bool>,
}

/// `GetNotesListSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetNotesListSuccessfulResponseDto {
    /// List of notes
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub notes: Vec<GetNoteSchema>,
}

/// `InboundDndSettingSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InboundDndSettingSchema {
    /// Inbound DND status for this channel
    /// Allowed values: `active`, `inactive`.
    /// Required by the API.
    pub status: String,
    /// Custom message associated with the inbound DND setting
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// `InboundDndSettingsSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InboundDndSettingsSchema {
    /// Inbound DND settings applied to all channels
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub all: Option<InboundDndSettingSchema>,
}

/// `LargeTextField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LargeTextField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Large text value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<String>,
}

/// `MonetoryField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MonetoryField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Monetary value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<serde_json::Value>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<serde_json::Value>,
}

/// `MultiSelectField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MultiSelectField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Array of selected values for the custom field (preferred).
    #[serde(rename = "fieldValue", default, skip_serializing_if = "Vec::is_empty")]
    pub field_value: Vec<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(rename = "field_value", default, skip_serializing_if = "Vec::is_empty")]
    pub field_value_alt: Vec<String>,
}

/// `NotesDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NotesDTO {
    /// User Id of the note author
    #[serde(rename = "userId", default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Body content of the note
    /// Required by the API.
    pub body: String,
    /// Title of the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Hex color code for the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Whether the note is pinned
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pinned: Option<bool>,
}

/// `NumericField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NumericField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Numeric value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<serde_json::Value>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<serde_json::Value>,
}

/// `RadioField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RadioField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Selected radio option value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<String>,
}

/// `SearchBodyV2DTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchBodyV2DTO {
    /// The spec defines no fields for this schema.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// `SingleSelectField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SingleSelectField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Selected option value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<String>,
}

/// `TagsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TagsDTO {
    /// List of tags to add or remove
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
}

/// `TaskByIsSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TaskByIsSuccessfulResponseDto {
    /// Task details
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub task: Option<TaskSchema>,
}

/// `TaskSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TaskSchema {
    /// Unique identifier of the task
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Title of the task
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Body or description of the task
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// User Id to whom the task is assigned
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Due date of the task (ISO 8601 format)
    #[serde(rename = "dueDate", default, skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    /// Whether the task is completed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed: Option<bool>,
    /// Contact Id associated with the task
    #[serde(rename = "contactId", default, skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
}

/// `TasksListSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TasksListSuccessfulResponseDto {
    /// List of tasks
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tasks: Vec<TaskSchema>,
}

/// `TextField` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TextField {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Text value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<String>,
}

/// `UpdateContactDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateContactDtoV3 {
    /// First name of the contact
    #[serde(rename = "firstName", default, skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name of the contact
    #[serde(rename = "lastName", default, skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Full name of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Email address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Phone number of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Street address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address1: Option<String>,
    /// City of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// State of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Postal code of the contact
    #[serde(
        rename = "postalCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    /// Website URL of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// Timezone of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Whether Do Not Disturb is enabled for the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dnd: Option<bool>,
    /// Inbound DND settings per channel for the contact
    #[serde(
        rename = "inboundDndSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_dnd_settings: Option<InboundDndSettingsSchema>,
    /// This field will overwrite all current tags associated with the contact. To update a
    /// tags, it is recommended to use the Add Tag or Remove Tag API instead.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// List of custom field values to assign to the contact
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<serde_json::Value>,
    /// Source from which the contact was updated
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// The birth date of the contact. Supported formats: YYYY/MM/DD, MM/DD/YYYY, YYYY-MM-DD,
    /// MM-DD-YYYY, YYYY.MM.DD, MM.DD.YYYY, YYYY_MM_DD, MM_DD_YYYY
    #[serde(
        rename = "dateOfBirth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub date_of_birth: Option<serde_json::Value>,
    /// Country code of the contact (ISO 3166-1 alpha-2), Refer country list from documentaion,
    /// documentation has list of all countries
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// User's Id
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Per-channel DND settings for the contact
    #[serde(
        rename = "dndSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dnd_settings: Option<DndSettingsSchemaV3>,
}

/// `UpdateContactsSuccessfulResponseDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateContactsSuccessfulResponseDtoV3 {
    /// Whether the update operation succeeded
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<bool>,
    /// Contact details
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<GetContactByIdSchemaV3>,
}

/// `UpdateNoteDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateNoteDTO {
    /// User Id of the note author
    #[serde(rename = "userId", default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Body content of the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// Title of the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Hex color code for the note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Whether the note is pinned
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pinned: Option<bool>,
}

/// `UpdateTagsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateTagsDTO {
    /// list of contact ids to be processed
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub contacts: Vec<String>,
    /// list of tags to be added or removed
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// location id from where the bulk request is executed
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Option to implement remove all tags. if true, all tags will be removed from the
    /// contacts. Can only be used with remove type.
    #[serde(
        rename = "removeAllTags",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub remove_all_tags: Option<bool>,
}

/// `UpdateTagsResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateTagsResponseDTO {
    /// Indicates if the operation was successful
    /// Required by the API.
    pub succeeded: bool,
    /// Legacy misspelling of `succeeded`. Deprecated; use `succeeded`.
    /// Required by the API.
    pub succeded: bool,
    /// Number of errors encountered during the operation
    /// Required by the API.
    #[serde(rename = "errorCount")]
    pub error_count: f64,
    /// Responses for each contact processed
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub responses: Vec<String>,
}

/// `UpdateTaskBody` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateTaskBody {
    /// Title of the task
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Body or description of the task
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// Due date of the task (ISO 8601 format)
    #[serde(rename = "dueDate", default, skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    /// Whether the task is completed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed: Option<bool>,
    /// User Id to whom the task is assigned
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
}

/// `UpdateTaskStatusParams` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateTaskStatusParams {
    /// Whether the task is completed
    /// Required by the API.
    pub completed: bool,
}

/// `UpsertContactDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpsertContactDtoV3 {
    /// First name of the contact
    #[serde(rename = "firstName", default, skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name of the contact
    #[serde(rename = "lastName", default, skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Full name of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Email address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Location Id the contact should be created under
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Gender of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    /// Phone number of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Street address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address1: Option<String>,
    /// City of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// State of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Postal code of the contact
    #[serde(
        rename = "postalCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    /// Website URL of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// Timezone of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Whether Do Not Disturb is enabled for the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dnd: Option<bool>,
    /// Inbound DND settings per channel for the contact
    #[serde(
        rename = "inboundDndSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_dnd_settings: Option<InboundDndSettingsSchema>,
    /// This field will overwrite all current tags associated with the contact. To update a
    /// tags, it is recommended to use the Add Tag or Remove Tag API instead.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    /// List of custom field values to assign to the contact
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<serde_json::Value>,
    /// Source from which the contact was created
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// The birth date of the contact. Supported formats: YYYY/MM/DD, MM/DD/YYYY, YYYY-MM-DD,
    /// MM-DD-YYYY, YYYY.MM.DD, MM.DD.YYYY, YYYY_MM_DD, MM_DD_YYYY
    #[serde(
        rename = "dateOfBirth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub date_of_birth: Option<serde_json::Value>,
    /// Country code of the contact (ISO 3166-1 alpha-2)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Company name of the contact
    #[serde(
        rename = "companyName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub company_name: Option<String>,
    /// User's Id
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Controls whether to create a new contact or update an existing duplicate. **Scenario
    /// 1:** If this value is `true` and the location allows duplicate contacts, a new contact
    /// will be created immediately without checking for duplicates. **Scenario 2:** If this
    /// value is `true` but the location does not allow duplicate contacts, this field is
    /// ignored and the normal upsert behavior applies: the API will search for an existing
    /// duplicate contact, update it if found, or create a new contact if not found. **Scenario
    /// 3:** If this value is `false` or not provided, the normal upsert behavior applies
    /// regardless of the location's duplicate contact setting.
    #[serde(
        rename = "createNewIfDuplicateAllowed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub create_new_if_duplicate_allowed: Option<bool>,
    /// Per-channel DND settings for the contact
    #[serde(
        rename = "dndSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dnd_settings: Option<DndSettingsSchemaV3>,
}

/// `UpsertContactsSuccessfulResponseDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpsertContactsSuccessfulResponseDtoV3 {
    /// Whether a new contact was created (true) or an existing one was updated (false)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub new: Option<bool>,
    /// Contact details
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<GetContactByIdSchemaV3>,
    /// Unique trace identifier for this operation
    #[serde(rename = "traceId", default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
}

/// `customFieldsInputArraySchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputArraySchema {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Array value for the custom field (preferred).
    #[serde(rename = "fieldValue", default, skip_serializing_if = "Vec::is_empty")]
    pub field_value: Vec<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(rename = "field_value", default, skip_serializing_if = "Vec::is_empty")]
    pub field_value_alt: Vec<String>,
}

/// `customFieldsInputObjectSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputObjectSchema {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Object value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<serde_json::Value>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<serde_json::Value>,
}

/// `customFieldsInputStringSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputStringSchema {
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Value for the custom field (preferred).
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<String>,
    /// Deprecated. Use `fieldValue` instead.
    #[serde(
        rename = "field_value",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value_alt: Option<String>,
}
