//! `knowledge-base` data models for GoHighLevel API V3 (38 types).
//!
//! Generated from HighLevel's official OpenAPI spec for the
//! **Knowledge Base** module. Every endpoint that uses these types, with its
//! parameters, required scopes and enum values, is documented in the
//! [`knowledge-base` API reference](https://github.com/Shahroz/ghl-rs/blob/main/docs/api/knowledge-base.md).
//!
//! Enable with `features = ["knowledge-base"]`.
// @generated by xtask/generate_models.py — do not edit by hand.
// Source: https://github.com/GoHighLevel/highlevel-api-docs
// Doc comments are HighLevel's own field descriptions, reflowed verbatim, so
// they aren't held to rustdoc's markdown conventions.
#![allow(
    missing_docs,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items
)]

use serde::{Deserialize, Serialize};

/// `AddFaqDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AddFaqDTO {
    /// location ID as string
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// faq question as a string
    /// Required by the API.
    pub question: String,
    /// faq answer as a string
    /// Required by the API.
    pub answer: String,
    /// knowledge base ID as string
    /// Required by the API.
    #[serde(rename = "knowledgeBaseId")]
    pub knowledge_base_id: String,
}

/// `BadRequestDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BadRequestDTO {
    #[serde(
        rename = "statusCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_code: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// `CrawledUrlDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CrawledUrlDTO {
    /// Unique identifier for the URL
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The actual URL that was crawled
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Title of the webpage
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Current processing status of the URL
    /// Allowed values: `Pending`, `Processing`, `Successful`, `Failed`, `Existing`,
    /// `Restricted`, `Cancelled`, `Aborted`, `Training`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Location ID associated with this URL
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Knowledge base ID this URL belongs to
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "knowledgeBaseId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_base_id: Option<String>,
    /// URL to the stored content file
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Whether the content was edited by user
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "contentEditedByUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub content_edited_by_user: Option<bool>,
    /// Last updated timestamp
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

/// `CrawlingAggregateDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CrawlingAggregateDTO {
    /// Status grouping identifier
    /// Allowed values: `Pending`, `Processing`, `Successful`, `Failed`, `Existing`,
    /// `Restricted`, `Cancelled`, `Aborted`, `Training`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "_id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Array of records for this status
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub records: Vec<CrawlingRecordDTO>,
}

/// `CrawlingRecordDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CrawlingRecordDTO {
    /// URL being crawled
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Unique record identifier
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Page title (for successful/pending records)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Error details (for failed records)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorDetailsDTO>,
}

/// `CrawlingStatusDataDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CrawlingStatusDataDTO {
    /// Aggregated crawling results by status
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub aggregate: Vec<CrawlingAggregateDTO>,
    /// Detailed operation information
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "operationDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub operation_details: Option<OperationDetailsDTO>,
}

/// `CrawlingStatusResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CrawlingStatusResponseDTO {
    /// Indicates if the operation was successful
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Detailed crawling status data
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<CrawlingStatusDataDTO>,
}

/// `CreateFaqResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateFaqResponseDTO {
    /// Success status of the operation
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Created FAQ details
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub faq: Option<FaqResponseDTO>,
}

/// `CreateKnowledgeBaseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateKnowledgeBaseDTO {
    /// Required by the API.
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
}

/// `CreateKnowledgeBaseResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateKnowledgeBaseResponseDTO {
    /// Success status of the operation
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Created knowledge base details
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<KnowledgeBaseDataDTO>,
}

/// `DeleteFaqResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteFaqResponseDTO {
    /// Success status of the delete operation
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

/// `DeleteKnowledgeBaseResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteKnowledgeBaseResponseDTO {
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

/// `DeleteWebsiteUrlRequestDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteWebsiteUrlRequestDTO {
    /// knowledge base ID as string
    /// Required by the API.
    #[serde(rename = "knowledgeBaseId")]
    pub knowledge_base_id: String,
    /// location ID as string
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// List of trained urls ids ( fetched from the Get all trained page links by knowledge base
    /// endpoint)
    /// Required by the API.
    #[serde(rename = "urlIds", default, skip_serializing_if = "Vec::is_empty")]
    pub url_ids: Vec<String>,
}

/// `DeleteWebsiteUrlResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteWebsiteUrlResponseDTO {
    /// Indicates if the operation was successful
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

/// `DiscoverWebsiteDataDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DiscoverWebsiteDataDTO {
    /// Operation ID for tracking the discovery process
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "operationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub operation_id: Option<String>,
    /// Current status of the website discovery operation
    /// Allowed values: `Pending`, `Processing`, `Successful`, `Failed`, `Existing`,
    /// `Restricted`, `Cancelled`, `Aborted`, `Training`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The URL being discovered/crawled
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// `DiscoverWebsiteRequestDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DiscoverWebsiteRequestDTO {
    /// Location ID as string
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Website URL as string
    /// Required by the API.
    pub url: String,
    /// Mode as string
    /// Allowed values: `Exact`, `Path`, `Domain`.
    /// Required by the API.
    pub option: String,
    /// knowledge base ID as string
    /// Required by the API.
    #[serde(rename = "knowledgeBaseId")]
    pub knowledge_base_id: String,
}

/// `DiscoverWebsiteResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DiscoverWebsiteResponseDTO {
    /// Indicates if the operation was successful
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Data containing operation details
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<DiscoverWebsiteDataDTO>,
}

/// `ErrorDetailsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ErrorDetailsDTO {
    /// Error stack trace
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stack: Option<String>,
    /// Error response message
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<String>,
    /// HTTP status code
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<f64>,
    /// Additional options (nullable)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<serde_json::Value>,
    /// Error message
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Error name/type
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// `FaqResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FaqResponseDTO {
    /// FAQ ID as string
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// FAQ question
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,
    /// FAQ question in lowercase
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "questionLowerCase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub question_lower_case: Option<String>,
    /// FAQ answer
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    /// Knowledge base ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "knowledgeBaseId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_base_id: Option<String>,
    /// Location ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Trained URL ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "trainedUrlId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trained_url_id: Option<String>,
    /// Whether the FAQ is deleted
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Date when FAQ was created
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Date when FAQ was last updated
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

/// `GetAllKnowledgeBasesPaginatedDataDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetAllKnowledgeBasesPaginatedDataDTO {
    /// Array of knowledge bases
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "knowledgeBases",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub knowledge_bases: Vec<KnowledgeBaseListItemDTO>,
    /// Total count of all active knowledge bases
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "activeCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub active_count: Option<f64>,
    /// Whether there are more knowledge bases available
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "hasMore", default, skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// ID of the last knowledge base in this page (use for next page request)
    #[serde(
        rename = "lastKnowledgeBaseId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_knowledge_base_id: Option<String>,
}

/// `GetAllKnowledgeBasesPaginatedResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetAllKnowledgeBasesPaginatedResponseDTO {
    /// Success status of the operation
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Paginated knowledge bases data
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<GetAllKnowledgeBasesPaginatedDataDTO>,
}

/// `GetAllUrlsByKnowledgeBaseResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetAllUrlsByKnowledgeBaseResponseDTO {
    /// Total count of URLs in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<f64>,
    /// Array of crawled URLs with their details
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub urls: Vec<CrawledUrlDTO>,
}

/// `GetKnowledgeBaseByIdDataDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetKnowledgeBaseByIdDataDTO {
    /// Knowledge base ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Knowledge base name
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Knowledge base name in lowercase
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "nameLowerCase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub name_lower_case: Option<String>,
    /// Location ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Whether the knowledge base is deleted
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Date when knowledge base was created
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Date when knowledge base was last updated
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Knowledge base metadata with content counts
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "kbMetadata",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub kb_metadata: Option<KnowledgeBaseMetadataDTO>,
    /// Whether the knowledge base is default or not
    #[serde(rename = "isDefault", default, skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
}

/// `GetKnowledgeBaseByIdResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetKnowledgeBaseByIdResponseDTO {
    /// Success status of the operation
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Knowledge base details
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<GetKnowledgeBaseByIdDataDTO>,
}

/// `InternalServerErrorDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InternalServerErrorDTO {
    #[serde(
        rename = "statusCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_code: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// `KnowledgeBaseDataDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct KnowledgeBaseDataDTO {
    /// Knowledge base ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Knowledge base name
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Knowledge base name in lowercase
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "nameLowerCase",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub name_lower_case: Option<String>,
    /// Location ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Knowledge base metadata
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "kbMetadata",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub kb_metadata: Option<serde_json::Value>,
    /// Whether the knowledge base is deleted
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Date when knowledge base was created
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Date when knowledge base was last updated
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

/// `KnowledgeBaseListItemDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct KnowledgeBaseListItemDTO {
    /// Knowledge base ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Knowledge base name
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Date when knowledge base was created
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

/// `KnowledgeBaseMetadataDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct KnowledgeBaseMetadataDTO {
    /// Number of FAQs in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub faqs: Option<f64>,
    /// Number of URLs in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub urls: Option<f64>,
    /// Number of rich text documents in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "richText", default, skip_serializing_if = "Option::is_none")]
    pub rich_text: Option<f64>,
    /// Number of files in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files: Option<f64>,
    /// Number of web searche configs in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "webSearches",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub web_searches: Option<f64>,
    /// Number of tables in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tables: Option<f64>,
}

/// `ListFaqsResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListFaqsResponseDTO {
    /// Total count of all FAQs in the knowledge base
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<f64>,
    /// Array of FAQ objects
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub faqs: Vec<FaqResponseDTO>,
    /// Last FAQ ID for pagination (use as lastFaqId in next request)
    #[serde(rename = "lastFaqId", default, skip_serializing_if = "Option::is_none")]
    pub last_faq_id: Option<String>,
    /// Whether there are more FAQs available
    #[serde(rename = "hasMore", default, skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
}

/// `OperationDetailsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OperationDetailsDTO {
    /// Number of URLs discovered
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "discoveredUrlsCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub discovered_urls_count: Option<f64>,
    /// Number of URLs successfully trained
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "trainedUrlsCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trained_urls_count: Option<f64>,
    /// Operation unique identifier
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "_id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Associated location ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Current operation status
    /// Allowed values: `Pending`, `Processing`, `Successful`, `Failed`, `Existing`,
    /// `Restricted`, `Cancelled`, `Aborted`, `Training`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Base URL being crawled
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Crawling mode used
    /// Allowed values: `Exact`, `Path`, `Domain`.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    /// Knowledge base ID
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "knowledgeBaseId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_base_id: Option<String>,
    /// Operation creation timestamp
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Last update timestamp
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Version field
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "__v", default, skip_serializing_if = "Option::is_none")]
    pub v: Option<f64>,
    /// Robots.txt file content
    #[serde(
        rename = "robotsFileData",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub robots_file_data: Option<String>,
}

/// `TrainDiscoveredUrlsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TrainDiscoveredUrlsDTO {
    /// Location ID as string
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// List of Object ids of the discovered urls
    /// Required by the API.
    #[serde(rename = "urlIds", default, skip_serializing_if = "Vec::is_empty")]
    pub url_ids: Vec<String>,
    /// knowledge base id
    /// Required by the API.
    #[serde(rename = "knowledgeBaseId")]
    pub knowledge_base_id: String,
    /// operation id as string
    /// Required by the API.
    #[serde(rename = "operationId")]
    pub operation_id: String,
}

/// `TrainDiscoveredUrlsResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TrainDiscoveredUrlsResponseDTO {
    /// Indicates if the operation was successful
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

/// `UnauthorizedDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UnauthorizedDTO {
    #[serde(
        rename = "statusCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_code: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `UnprocessableDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UnprocessableDTO {
    #[serde(
        rename = "statusCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_code: Option<f64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub message: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `UpdateFaqBodyDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateFaqBodyDTO {
    /// faq question as a string
    /// Required by the API.
    pub question: String,
    /// faq answer as a string
    /// Required by the API.
    pub answer: String,
}

/// `UpdateFaqResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateFaqResponseDTO {
    /// Success status of the update operation
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

/// `UpdateKnowledgeBaseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateKnowledgeBaseDTO {
    /// field to update the name of the knowledge base
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// field to update the description of the knowledge base
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// `UpdateKnowledgeBaseResponseDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateKnowledgeBaseResponseDTO {
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}
