//! `opportunities` data models for GoHighLevel API V3 (26 types).
//!
//! Generated from HighLevel's official OpenAPI spec for the
//! **Opportunities** module. Every endpoint that uses these types, with its
//! parameters, required scopes and enum values, is documented in the
//! [`opportunities` API reference](https://github.com/Shahroz/ghl-rs/blob/main/docs/api/opportunities.md).
//!
//! Enable with `features = ["opportunities"]`.
// @generated by xtask/generate_models.py — do not edit by hand.
// Source: https://github.com/GoHighLevel/highlevel-api-docs
// Doc comments are HighLevel's own field descriptions, reflowed verbatim, so
// they aren't held to rustdoc's markdown conventions.
#![allow(
    missing_docs,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items
)]

use serde::{Deserialize, Serialize};

/// `AdditionalDetailsDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AdditionalDetailsDTO {
    /// Include notes in the response
    /// Required by the API.
    pub notes: bool,
    /// Include tasks in the response
    /// Required by the API.
    pub tasks: bool,
    /// Include calendar events in the response
    /// Required by the API.
    #[serde(rename = "calendarEvents")]
    pub calendar_events: bool,
    /// Include unread conversations count in the response
    /// Required by the API.
    #[serde(rename = "unReadConversations")]
    pub un_read_conversations: bool,
}

/// `CreateAddFollowersSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateAddFollowersSuccessfulResponseDto {
    /// Current list of all follower user IDs after the operation
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    /// User IDs that were successfully added as followers
    #[serde(
        rename = "followersAdded",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub followers_added: Vec<String>,
}

/// `CreateDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateDtoV3 {
    /// pipeline Id
    /// Required by the API.
    #[serde(rename = "pipelineId")]
    pub pipeline_id: String,
    /// Identifier of the location (sub-account)
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Name of the opportunity
    /// Required by the API.
    pub name: String,
    /// Identifier of the pipeline stage
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    /// Current status of the opportunity
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    /// Required by the API.
    pub status: String,
    /// Identifier of the contact linked to the opportunity
    /// Required by the API.
    #[serde(rename = "contactId")]
    pub contact_id: String,
    /// Monetary value of the opportunity
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<f64>,
    /// Expected close date. Supported formats: YYYY/MM/DD, MM/DD/YYYY, YYYY-MM-DD, MM-DD-YYYY,
    /// YYYY.MM.DD, MM.DD.YYYY, or ISO 8601
    #[serde(
        rename = "forecastExpectedCloseDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_expected_close_date: Option<String>,
    /// Forecast probability
    #[serde(
        rename = "forecastProbability",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_probability: Option<f64>,
    /// Identifier of the user the opportunity is assigned to
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Add custom fields to opportunities.
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<serde_json::Value>,
}

/// `CustomFieldResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldResponseSchema {
    /// Unique identifier of the custom field
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The value of the custom field
    /// Multiple possible shapes in the spec; raw JSON.
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<serde_json::Value>,
}

/// `DeleteFollowersSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteFollowersSuccessfulResponseDto {
    /// Current list of all follower user IDs after the operation
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    /// User IDs that were successfully removed as followers
    #[serde(
        rename = "followersRemoved",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub followers_removed: Vec<String>,
}

/// `DeleteUpdateOpportunitySuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteUpdateOpportunitySuccessfulResponseDto {
    /// Indicates whether the operation was successful. Deprecated — use `success` instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub succeded: Option<bool>,
    /// Indicates whether the operation was successful
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

/// `FollowersDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FollowersDTO {
    /// Array of user IDs to add or remove as followers (max 10)
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
}

/// `GetPipelinesSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetPipelinesSuccessfulResponseDto {
    /// List of pipelines for the location
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pipelines: Vec<PipelinesResponseSchema>,
}

/// `GetPostOpportunitySuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetPostOpportunitySuccessfulResponseDto {
    /// The created or retrieved opportunity object
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opportunity: Option<SearchOpportunitiesResponseSchema>,
}

/// `LostReasonResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LostReasonResponseSchema {
    /// lost reason id
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// lost reason name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// location id
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// updated at
    /// Format: date-time (ISO-8601 string).
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// created at
    /// Format: date-time (ISO-8601 string).
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

/// `LostReasonsResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LostReasonsResponseSchema {
    /// List of lost reasons for the location
    #[serde(rename = "lostReasons", default, skip_serializing_if = "Vec::is_empty")]
    pub lost_reasons: Vec<LostReasonResponseSchema>,
    /// Total number of lost reasons matching the query
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
}

/// `OpportunitySearchBodyDTO` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OpportunitySearchBodyDTO {
    /// Location Id
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// Full-text search query string (max 75 characters)
    /// Required by the API.
    pub query: String,
    /// Maximum number of results to return per page
    /// Required by the API.
    pub limit: f64,
    /// Page number (0-indexed)
    /// Required by the API.
    pub page: f64,
    /// Search-after cursor values for deep pagination
    /// Required by the API.
    #[serde(rename = "searchAfter", default, skip_serializing_if = "Vec::is_empty")]
    pub search_after: Vec<String>,
    /// Flags to include additional related entities in the response
    /// Required by the API.
    #[serde(rename = "additionalDetails")]
    pub additional_details: AdditionalDetailsDTO,
}

/// `PipelinesResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PipelinesResponseSchema {
    /// Unique identifier of the pipeline
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the pipeline
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Stages belonging to this pipeline
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub stages: Vec<Vec<serde_json::Value>>,
    /// Whether the pipeline is shown in the funnel view
    #[serde(
        rename = "showInFunnel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub show_in_funnel: Option<bool>,
    /// Whether the pipeline is shown in the pie chart view
    #[serde(
        rename = "showInPieChart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub show_in_pie_chart: Option<bool>,
    /// Identifier of the location (sub-account) this pipeline belongs to
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Whether stage-level win probability is enabled for this pipeline
    #[serde(
        rename = "useOpportunityProbability",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub use_opportunity_probability: Option<bool>,
    /// How pipeline/stage colors are rendered
    /// Allowed values: `dot`, `bg-tint`, `none`.
    #[serde(
        rename = "colorRenderMode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub color_render_mode: Option<String>,
}

/// `PostSearchSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostSearchSuccessfulResponseDto {
    /// List of opportunities matching the search criteria
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub opportunities: Vec<SearchOpportunitiesResponseSchema>,
    /// Total number of opportunities matching the query
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// Per-stage totals when pipeline filter is present
    #[serde(
        rename = "stageAggregations",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub stage_aggregations: Vec<StageAggregationResponseDto>,
    /// Aggregation results keyed by aggregation name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aggregations: Option<serde_json::Value>,
}

/// `SearchMetaResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchMetaResponseSchema {
    /// Total number of opportunities matching the query
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// URL to retrieve the next page of results
    #[serde(
        rename = "nextPageUrl",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_url: Option<String>,
    /// Cursor id to use for pagination (startAfterId param)
    #[serde(
        rename = "startAfterId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start_after_id: Option<String>,
    /// Cursor timestamp to use for pagination (startAfter param)
    #[serde(
        rename = "startAfter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start_after: Option<f64>,
    /// Current page number
    #[serde(
        rename = "currentPage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub current_page: Option<f64>,
    /// Next page number
    #[serde(rename = "nextPage", default, skip_serializing_if = "Option::is_none")]
    pub next_page: Option<f64>,
    /// Previous page number
    #[serde(rename = "prevPage", default, skip_serializing_if = "Option::is_none")]
    pub prev_page: Option<f64>,
}

/// `SearchOpportunitiesContactResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchOpportunitiesContactResponseSchema {
    /// Unique identifier of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Full name of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Company name associated with the contact
    #[serde(
        rename = "companyName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub company_name: Option<String>,
    /// Email address of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Phone number of the contact
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Tags associated with the contact
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
}

/// `SearchOpportunitiesResponseSchema` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchOpportunitiesResponseSchema {
    /// Unique identifier of the opportunity
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the opportunity
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Monetary value of the opportunity
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<f64>,
    /// Identifier of the pipeline the opportunity belongs to
    #[serde(
        rename = "pipelineId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_id: Option<String>,
    /// Identifier of the pipeline stage the opportunity is in
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    /// Identifier of the user the opportunity is assigned to
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Current status of the opportunity
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Source of the opportunity
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// ISO 8601 timestamp of the last status change
    #[serde(
        rename = "lastStatusChangeAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_status_change_at: Option<String>,
    /// ISO 8601 timestamp of the last stage change
    #[serde(
        rename = "lastStageChangeAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_stage_change_at: Option<String>,
    /// ISO 8601 timestamp of the last action on the opportunity
    #[serde(
        rename = "lastActionDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_action_date: Option<String>,
    /// Index version of the opportunity record
    #[serde(
        rename = "indexVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub index_version: Option<String>,
    /// ISO 8601 timestamp when the opportunity was created
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// ISO 8601 timestamp when the opportunity was last updated
    #[serde(rename = "updatedAt", default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Expected close date for the forecast (YYYY-MM-DD)
    #[serde(
        rename = "forecastExpectedCloseDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_expected_close_date: Option<String>,
    /// Original forecast close date before any slippage (YYYY-MM-DD)
    #[serde(
        rename = "forecastOriginalCloseDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_original_close_date: Option<String>,
    /// Number of times the close date has slipped
    #[serde(
        rename = "forecastSlippageCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_slippage_count: Option<f64>,
    /// Total days the close date has slipped
    #[serde(
        rename = "forecastDaysSlipped",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_days_slipped: Option<f64>,
    /// ISO 8601 timestamp of the last close-date slip
    #[serde(
        rename = "forecastLastSlippedAt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_last_slipped_at: Option<String>,
    /// Forecast win probability percentage (0–100)
    #[serde(
        rename = "forecastProbability",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_probability: Option<f64>,
    /// Effective win probability after stage and forecast adjustments (0–100)
    #[serde(
        rename = "effectiveProbability",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_probability: Option<f64>,
    /// Identifier of the contact linked to the opportunity
    #[serde(rename = "contactId", default, skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
    /// Identifier of the location (sub-account) the opportunity belongs to
    #[serde(
        rename = "locationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub location_id: Option<String>,
    /// Contact details associated with the opportunity
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<SearchOpportunitiesContactResponseSchema>,
    /// Notes attached to the opportunity
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub notes: Vec<Vec<serde_json::Value>>,
    /// Tasks attached to the opportunity
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tasks: Vec<Vec<serde_json::Value>>,
    /// Calendar events attached to the opportunity
    #[serde(
        rename = "calendarEvents",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub calendar_events: Vec<Vec<serde_json::Value>>,
    /// Identifier of the lost reason if the opportunity was marked lost
    #[serde(
        rename = "lostReasonId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lost_reason_id: Option<String>,
    /// Custom fields associated with the opportunity
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<CustomFieldResponseSchema>,
    /// User IDs following this opportunity
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<Vec<serde_json::Value>>,
    /// External object identifier for integrations
    #[serde(
        rename = "externalObjectId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub external_object_id: Option<String>,
}

/// `SearchSuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchSuccessfulResponseDto {
    /// List of opportunities matching the search criteria
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub opportunities: Vec<SearchOpportunitiesResponseSchema>,
    /// Pagination metadata for the result set
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<SearchMetaResponseSchema>,
    /// Aggregation results keyed by aggregation name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aggregations: Option<serde_json::Value>,
}

/// `StageAggregationResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StageAggregationResponseDto {
    /// Identifier of the pipeline stage being aggregated
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    /// Total number of opportunities in this stage
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "totalCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub total_count: Option<f64>,
    /// Total monetary value of all opportunities in this stage
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "totalValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub total_value: Option<f64>,
    /// Probability-weighted total value of opportunities in this stage
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "weightedValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub weighted_value: Option<f64>,
    /// Total value of open opportunities in this stage
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "openValue", default, skip_serializing_if = "Option::is_none")]
    pub open_value: Option<f64>,
    /// Probability-weighted value of open opportunities in this stage
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(
        rename = "openWeightedValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub open_weighted_value: Option<f64>,
    /// Total value of won opportunities in this stage
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(rename = "wonValue", default, skip_serializing_if = "Option::is_none")]
    pub won_value: Option<f64>,
}

/// `UpdateOpportunityDtoV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateOpportunityDtoV3 {
    /// pipeline Id
    #[serde(
        rename = "pipelineId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_id: Option<String>,
    /// Name of the opportunity
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Identifier of the pipeline stage
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    /// Current status of the opportunity
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Monetary value of the opportunity
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<f64>,
    /// Expected close date. Supported formats: YYYY/MM/DD, MM/DD/YYYY, YYYY-MM-DD, MM-DD-YYYY,
    /// YYYY.MM.DD, MM.DD.YYYY, or ISO 8601
    #[serde(
        rename = "forecastExpectedCloseDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_expected_close_date: Option<String>,
    /// Forecast probability
    #[serde(
        rename = "forecastProbability",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_probability: Option<f64>,
    /// Identifier of the user the opportunity is assigned to
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// Update custom fields to opportunities.
    /// Multiple possible shapes in the spec; raw JSON.
    #[serde(
        rename = "customFields",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub custom_fields: Vec<serde_json::Value>,
}

/// `UpdateStatusDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateStatusDto {
    /// New status for the opportunity
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    /// Required by the API.
    pub status: String,
    /// lost reason Id
    #[serde(
        rename = "lostReasonId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lost_reason_id: Option<String>,
}

/// `UpsertOpportunityDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpsertOpportunityDto {
    /// opportunityId
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// pipeline Id
    /// Required by the API.
    #[serde(rename = "pipelineId")]
    pub pipeline_id: String,
    /// locationId
    /// Required by the API.
    #[serde(rename = "locationId")]
    pub location_id: String,
    /// contactId
    /// Required by the API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub followers: Vec<String>,
    /// isRemoveAllFollowers
    /// Required by the API.
    #[serde(rename = "isRemoveAllFollowers")]
    pub is_remove_all_followers: bool,
    /// followers action type
    /// Allowed values: `add`, `remove`.
    /// Required by the API.
    #[serde(rename = "followersActionType")]
    pub followers_action_type: String,
    /// name
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Current status of the opportunity
    /// Allowed values: `open`, `won`, `lost`, `abandoned`, `all`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Identifier of the pipeline stage
    #[serde(
        rename = "pipelineStageId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline_stage_id: Option<String>,
    /// Monetary value of the opportunity
    #[serde(
        rename = "monetaryValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monetary_value: Option<serde_json::Value>,
    /// Expected close date. Supported formats: YYYY/MM/DD, MM/DD/YYYY, YYYY-MM-DD, MM-DD-YYYY,
    /// YYYY.MM.DD, MM.DD.YYYY, or ISO 8601
    #[serde(
        rename = "forecastExpectedCloseDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_expected_close_date: Option<String>,
    /// Forecast probability
    #[serde(
        rename = "forecastProbability",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_probability: Option<f64>,
    /// Identifier of the user the opportunity is assigned to
    #[serde(
        rename = "assignedTo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_to: Option<String>,
    /// lost reason Id
    #[serde(
        rename = "lostReasonId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lost_reason_id: Option<String>,
}

/// `UpsertOpportunitySuccessfulResponseDto` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpsertOpportunitySuccessfulResponseDto {
    /// Updated / New Opportunity
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opportunity: Option<serde_json::Value>,
    /// Indicates whether the opportunity was newly created (true) or updated (false)
    /// Required by the API.
    /// (Optional here so responses that omit it still parse.)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub new: Option<bool>,
}

/// `customFieldsInputArraySchemaV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputArraySchemaV3 {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Value of the custom field
    #[serde(rename = "fieldValue", default, skip_serializing_if = "Vec::is_empty")]
    pub field_value: Vec<String>,
}

/// `customFieldsInputObjectSchemaV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputObjectSchemaV3 {
    /// Pass either `id` or `key` of custom field
    /// Required by the API.
    pub id: String,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Value of the custom field
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<serde_json::Value>,
}

/// `customFieldsInputStringSchemaV3` from the GoHighLevel OpenAPI spec.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomFieldsInputStringSchemaV3 {
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Pass either `id` or `key` of custom field
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Value of the custom field
    #[serde(
        rename = "fieldValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub field_value: Option<String>,
}
