// @generated by xtask/generate_services.py — do not edit by hand.
//! `locations` — typed methods for all 32 API v3 operations
//! in this module.
//!
//! Access via [`Ghl::v3`](crate::Ghl::v3)`().locations()`. These endpoints send `Version: v3`.
//!
//! Request and response types come from [`ghl_models::v3::locations`](https://docs.rs/ghl-models/latest/ghl_models/v3/locations/); every endpoint is also documented in the
//! [`locations` API reference](https://github.com/Shahroz/ghl-rs/blob/main/docs/api/locations.md).
//!
//! Enable with `features = ["locations"]`.

#![allow(clippy::too_many_arguments)]

use crate::client::Ghl;
use crate::error::Result;
use ghl_models::v3::locations as models;

/// Typed access to the `locations` API v3 surface (32 operations). Obtained via
/// [`Ghl::v3`](crate::Ghl::v3)`().locations()`.
#[derive(Debug, Clone)]
pub struct LocationsService {
    pub(crate) client: Ghl,
}

impl LocationsService {
    pub(crate) fn new(client: Ghl) -> Self {
        Self { client }
    }
}

/// Query parameters for [`LocationsService::search`].
#[derive(Debug, Clone, Default)]
pub struct SearchParams {
    /// The company/agency id on which you want to perform the search
    pub company_id: Option<String>,
    /// The value by which the results should be skipped. Default will be 0
    pub skip: Option<String>,
    /// The value by which the results should be limited. Default will be 10
    pub limit: Option<String>,
    /// The order in which the results should be returned - Allowed values asc, desc.
    /// Default will be asc
    pub order: Option<String>,
    /// `email` query parameter.
    pub email: Option<String>,
}

impl SearchParams {
    /// Start from the parameters the API requires.
    pub fn new() -> Self {
        Self {
            ..Default::default()
        }
    }

    /// The company/agency id on which you want to perform the search
    pub fn company_id(mut self, v: impl Into<String>) -> Self {
        self.company_id = Some(v.into());
        self
    }

    /// The value by which the results should be skipped. Default will be 0
    pub fn skip(mut self, v: impl Into<String>) -> Self {
        self.skip = Some(v.into());
        self
    }

    /// The value by which the results should be limited. Default will be 10
    pub fn limit(mut self, v: impl Into<String>) -> Self {
        self.limit = Some(v.into());
        self
    }

    /// The order in which the results should be returned - Allowed values asc, desc.
    /// Default will be asc
    pub fn order(mut self, v: impl Into<String>) -> Self {
        self.order = Some(v.into());
        self
    }

    /// Set the `email` query parameter.
    pub fn email(mut self, v: impl Into<String>) -> Self {
        self.email = Some(v.into());
        self
    }

    fn to_query(&self) -> Vec<(String, String)> {
        let mut q: Vec<(String, String)> = Vec::new();
        if let Some(v) = &self.company_id {
            q.push(("companyId".into(), v.to_string()));
        }
        if let Some(v) = &self.skip {
            q.push(("skip".into(), v.to_string()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit".into(), v.to_string()));
        }
        if let Some(v) = &self.order {
            q.push(("order".into(), v.to_string()));
        }
        if let Some(v) = &self.email {
            q.push(("email".into(), v.to_string()));
        }
        q
    }
}

/// Query parameters for [`LocationsService::delete_sub_account_formerly_location`].
#[derive(Debug, Clone, Default)]
pub struct DeleteSubAccountFormerlyLocationParams {
    /// Boolean value to indicate whether to delete Twilio Account or not
    /// Required by the API.
    pub delete_twilio_account: bool,
}

impl DeleteSubAccountFormerlyLocationParams {
    /// Start from the parameters the API requires.
    pub fn new(delete_twilio_account: bool) -> Self {
        Self {
            delete_twilio_account,
        }
    }

    fn to_query(&self) -> Vec<(String, String)> {
        let q: Vec<(String, String)> = vec![(
            "deleteTwilioAccount".into(),
            self.delete_twilio_account.to_string(),
        )];
        q
    }
}

/// Query parameters for [`LocationsService::get_custom_fields`].
#[derive(Debug, Clone, Default)]
pub struct GetCustomFieldsParams {
    /// Model of the custom field you want to retrieve
    /// Allowed values: `contact`, `opportunity`, `all`.
    pub model: Option<String>,
}

impl GetCustomFieldsParams {
    /// Start from the parameters the API requires.
    pub fn new() -> Self {
        Self {
            ..Default::default()
        }
    }

    /// Model of the custom field you want to retrieve
    pub fn model(mut self, v: impl Into<String>) -> Self {
        self.model = Some(v.into());
        self
    }

    fn to_query(&self) -> Vec<(String, String)> {
        let mut q: Vec<(String, String)> = Vec::new();
        if let Some(v) = &self.model {
            q.push(("model".into(), v.to_string()));
        }
        q
    }
}

/// Query parameters for [`LocationsService::get_all_or_email_sms_templates`].
#[derive(Debug, Clone, Default)]
pub struct GetAllOrEmailSmsTemplatesParams {
    /// `deleted` query parameter.
    pub deleted: Option<bool>,
    /// `skip` query parameter.
    pub skip: Option<String>,
    /// `limit` query parameter.
    pub limit: Option<String>,
    /// `type` query parameter.
    /// Allowed values: `sms`, `email`, `whatsapp`.
    pub type_: Option<String>,
    /// Origin Id
    /// Required by the API.
    pub origin_id: String,
}

impl GetAllOrEmailSmsTemplatesParams {
    /// Start from the parameters the API requires.
    pub fn new(origin_id: impl Into<String>) -> Self {
        Self {
            origin_id: origin_id.into(),
            ..Default::default()
        }
    }

    /// Set the `deleted` query parameter.
    pub fn deleted(mut self, v: bool) -> Self {
        self.deleted = Some(v);
        self
    }

    /// Set the `skip` query parameter.
    pub fn skip(mut self, v: impl Into<String>) -> Self {
        self.skip = Some(v.into());
        self
    }

    /// Set the `limit` query parameter.
    pub fn limit(mut self, v: impl Into<String>) -> Self {
        self.limit = Some(v.into());
        self
    }

    /// Set the `type` query parameter.
    pub fn type_(mut self, v: impl Into<String>) -> Self {
        self.type_ = Some(v.into());
        self
    }

    fn to_query(&self) -> Vec<(String, String)> {
        let mut q: Vec<(String, String)> = vec![("originId".into(), self.origin_id.clone())];
        if let Some(v) = &self.deleted {
            q.push(("deleted".into(), v.to_string()));
        }
        if let Some(v) = &self.skip {
            q.push(("skip".into(), v.to_string()));
        }
        if let Some(v) = &self.limit {
            q.push(("limit".into(), v.to_string()));
        }
        if let Some(v) = &self.type_ {
            q.push(("type".into(), v.to_string()));
        }
        q
    }
}

impl LocationsService {
    /// Create Sub-Account (Formerly Location)
    ///
    /// Create a new Sub-Account (Formerly Location) based on the data provided :::info This
    /// feature is only available on Agency Pro ($497) plan. :::
    ///
    /// `POST /locations/`
    ///
    /// Requires scope: `locations.write`.
    pub async fn create_sub_account_formerly_location(
        &self,
        body: &models::CreateLocationDto,
    ) -> Result<models::CreateLocationSuccessfulResponseDto> {
        let query = Vec::new();
        self.client
            .send_versioned(
                reqwest::Method::POST,
                "/locations/",
                &query,
                Some(body),
                Some("v3"),
            )
            .await
    }

    /// Search
    ///
    /// Search Sub-Account (Formerly Location)
    ///
    /// `GET /locations/search`
    ///
    /// Requires scope: `locations.readonly`.
    pub async fn search(
        &self,
        params: &SearchParams,
    ) -> Result<models::SearchSuccessfulResponseDto> {
        let query = params.to_query();
        self.client
            .send_versioned(
                reqwest::Method::GET,
                "/locations/search",
                &query,
                None::<&()>,
                Some("v3"),
            )
            .await
    }

    /// Delete Sub-Account (Formerly Location)
    ///
    /// Delete a Sub-Account (Formerly Location) from the Agency
    ///
    /// `DELETE /locations/{locationId}`
    ///
    /// Requires scope: `locations.internal-access-only`.
    pub async fn delete_sub_account_formerly_location(
        &self,
        location_id: &str,
        params: &DeleteSubAccountFormerlyLocationParams,
    ) -> Result<models::LocationDeletedSuccessfulResponseDto> {
        let path = format!("/locations/{}", crate::services::encode(location_id));
        let query = params.to_query();
        self.client
            .send_versioned(
                reqwest::Method::DELETE,
                &path,
                &query,
                None::<&()>,
                Some("v3"),
            )
            .await
    }

    /// Get Sub-Account (Formerly Location)
    ///
    /// Get details of a Sub-Account (Formerly Location) by passing the sub-account id
    ///
    /// `GET /locations/{locationId}`
    ///
    /// Requires scope: `locations.readonly`.
    pub async fn get_sub_account_formerly_location(
        &self,
        location_id: &str,
    ) -> Result<models::GetLocationByIdSuccessfulResponseDto> {
        let path = format!("/locations/{}", crate::services::encode(location_id));
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Put Sub-Account (Formerly Location)
    ///
    /// Update a Sub-Account (Formerly Location) based on the data provided
    ///
    /// `PUT /locations/{locationId}`
    ///
    /// Requires scope: `locations.write`.
    pub async fn put_sub_account_formerly_location(
        &self,
        location_id: &str,
        body: &models::UpdateLocationDto,
    ) -> Result<models::CreateLocationSuccessfulResponseDto> {
        let path = format!("/locations/{}", crate::services::encode(location_id));
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::PUT, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Get Conversation Channel
    ///
    /// Get the conversation channel providers configured for a location by type (SMS or
    /// Email)
    ///
    /// `GET /locations/{locationId}/conversationChannels/{type}`
    ///
    /// Requires scope: `locations.readonly`.
    pub async fn get_conversation_channel(
        &self,
        location_id: &str,
        type_: &str,
    ) -> Result<models::GetConversationChannelListSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/conversationChannels/{}",
            crate::services::encode(location_id),
            crate::services::encode(type_)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Get Custom Fields
    ///
    /// `GET /locations/{locationId}/customFields`
    ///
    /// Requires scope: `locations/customFields.readonly`.
    pub async fn get_custom_fields(
        &self,
        location_id: &str,
        params: &GetCustomFieldsParams,
    ) -> Result<models::CustomFieldsListSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customFields",
            crate::services::encode(location_id)
        );
        let query = params.to_query();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Create Custom Field
    ///
    /// `POST /locations/{locationId}/customFields`
    ///
    /// Requires scope: `locations/customFields.write`.
    pub async fn create_custom_field(
        &self,
        location_id: &str,
        body: &models::CreateCustomFieldsDTO,
    ) -> Result<models::CustomFieldSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customFields",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::POST, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Uploads File to customFields
    ///
    /// `POST /locations/{locationId}/customFields/upload`
    ///
    /// Requires scope: `locations/customFields.write`.
    pub async fn uploads_file_to_custom_fields(
        &self,
        location_id: &str,
        body: &serde_json::Value,
    ) -> Result<models::FileUploadResponseDto> {
        let path = format!(
            "/locations/{}/customFields/upload",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::POST, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Delete Custom Field
    ///
    /// `DELETE /locations/{locationId}/customFields/{id}`
    pub async fn delete_custom_field(
        &self,
        location_id: &str,
        id: &str,
    ) -> Result<models::CustomFieldDeleteSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customFields/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(
                reqwest::Method::DELETE,
                &path,
                &query,
                None::<&()>,
                Some("v3"),
            )
            .await
    }

    /// Get Custom Field
    ///
    /// `GET /locations/{locationId}/customFields/{id}`
    pub async fn get_custom_field(
        &self,
        location_id: &str,
        id: &str,
    ) -> Result<models::CustomFieldSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customFields/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Update Custom Field
    ///
    /// `PUT /locations/{locationId}/customFields/{id}`
    pub async fn update_custom_field(
        &self,
        location_id: &str,
        id: &str,
        body: &models::UpdateCustomFieldsDTO,
    ) -> Result<models::CustomFieldSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customFields/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::PUT, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Get Custom Values
    ///
    /// `GET /locations/{locationId}/customValues`
    ///
    /// Requires scope: `locations/customValues.readonly`.
    pub async fn get_custom_values(
        &self,
        location_id: &str,
    ) -> Result<models::CustomValuesListSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customValues",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Create Custom Value
    ///
    /// `POST /locations/{locationId}/customValues`
    ///
    /// Requires scope: `locations/customValues.write`.
    pub async fn create_custom_value(
        &self,
        location_id: &str,
        body: &models::CustomValuesDTO,
    ) -> Result<models::CustomValueIdSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customValues",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::POST, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Delete Custom Value
    ///
    /// `DELETE /locations/{locationId}/customValues/{id}`
    pub async fn delete_custom_value(
        &self,
        location_id: &str,
        id: &str,
    ) -> Result<models::CustomValueDeleteSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customValues/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(
                reqwest::Method::DELETE,
                &path,
                &query,
                None::<&()>,
                Some("v3"),
            )
            .await
    }

    /// Get Custom Value
    ///
    /// `GET /locations/{locationId}/customValues/{id}`
    pub async fn get_custom_value(
        &self,
        location_id: &str,
        id: &str,
    ) -> Result<models::CustomValueIdSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customValues/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Update Custom Value
    ///
    /// `PUT /locations/{locationId}/customValues/{id}`
    pub async fn update_custom_value(
        &self,
        location_id: &str,
        id: &str,
        body: &models::CustomValuesDTO,
    ) -> Result<models::CustomValueIdSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/customValues/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::PUT, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Get Permissions
    ///
    /// Get Sub-Account (Formerly Location) permissions
    ///
    /// `GET /locations/{locationId}/permissions`
    ///
    /// Requires scope: `locations/write`.
    pub async fn get_permissions(
        &self,
        location_id: &str,
    ) -> Result<models::PermissionsResponseDto> {
        let path = format!(
            "/locations/{}/permissions",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Update Permissions
    ///
    /// Update Sub-Account (Formerly Location) permissions
    ///
    /// `PUT /locations/{locationId}/permissions`
    ///
    /// Requires scope: `locations/write`.
    pub async fn update_permissions(
        &self,
        location_id: &str,
        body: &models::UpdatePermissionsDto,
    ) -> Result<models::PermissionsResponseDto> {
        let path = format!(
            "/locations/{}/permissions",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::PUT, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Create Recurring Task
    ///
    /// `POST /locations/{locationId}/recurring-tasks`
    pub async fn create_recurring_task(
        &self,
        location_id: &str,
        body: &models::RecurringTaskCreateDTO,
    ) -> Result<models::RecurringTaskSingleResponseDTO> {
        let path = format!(
            "/locations/{}/recurring-tasks",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::POST, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Delete Recurring Task
    ///
    /// `DELETE /locations/{locationId}/recurring-tasks/{id}`
    pub async fn delete_recurring_task(
        &self,
        location_id: &str,
        id: &str,
    ) -> Result<models::DeleteRecurringTaskResponseDTO> {
        let path = format!(
            "/locations/{}/recurring-tasks/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(
                reqwest::Method::DELETE,
                &path,
                &query,
                None::<&()>,
                Some("v3"),
            )
            .await
    }

    /// Get Recurring Task By Id
    ///
    /// `GET /locations/{locationId}/recurring-tasks/{id}`
    pub async fn get_recurring_task_by_id(
        &self,
        location_id: &str,
        id: &str,
    ) -> Result<models::RecurringTaskSingleResponseDTO> {
        let path = format!(
            "/locations/{}/recurring-tasks/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Update Recurring Task
    ///
    /// `PUT /locations/{locationId}/recurring-tasks/{id}`
    pub async fn update_recurring_task(
        &self,
        location_id: &str,
        id: &str,
        body: &models::RecurringTaskUpdateDTO,
    ) -> Result<models::RecurringTaskSingleResponseDTO> {
        let path = format!(
            "/locations/{}/recurring-tasks/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::PUT, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Get Tags
    ///
    /// Get Sub-Account (Formerly Location) Tags
    ///
    /// `GET /locations/{locationId}/tags`
    ///
    /// Requires scope: `locations/tags.readonly`.
    pub async fn get_tags(
        &self,
        location_id: &str,
    ) -> Result<models::LocationTagsSuccessfulResponseDto> {
        let path = format!("/locations/{}/tags", crate::services::encode(location_id));
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Create Tag
    ///
    /// Create tag
    ///
    /// `POST /locations/{locationId}/tags`
    ///
    /// Requires scope: `locations/tags.write`.
    pub async fn create_tag(
        &self,
        location_id: &str,
        body: &models::TagBody,
    ) -> Result<models::LocationTagSuccessfulResponseDto> {
        let path = format!("/locations/{}/tags", crate::services::encode(location_id));
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::POST, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Delete tag
    ///
    /// `DELETE /locations/{locationId}/tags/{tagId}`
    pub async fn delete_tag(
        &self,
        location_id: &str,
        tag_id: &str,
    ) -> Result<models::LocationTagDeleteSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/tags/{}",
            crate::services::encode(location_id),
            crate::services::encode(tag_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(
                reqwest::Method::DELETE,
                &path,
                &query,
                None::<&()>,
                Some("v3"),
            )
            .await
    }

    /// Get tag by id
    ///
    /// `GET /locations/{locationId}/tags/{tagId}`
    pub async fn get_tag_by_id(
        &self,
        location_id: &str,
        tag_id: &str,
    ) -> Result<models::LocationTagSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/tags/{}",
            crate::services::encode(location_id),
            crate::services::encode(tag_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// Update tag
    ///
    /// `PUT /locations/{locationId}/tags/{tagId}`
    pub async fn update_tag(
        &self,
        location_id: &str,
        tag_id: &str,
        body: &models::TagBody,
    ) -> Result<models::LocationTagSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/tags/{}",
            crate::services::encode(location_id),
            crate::services::encode(tag_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::PUT, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// Task Search Filter
    ///
    /// Task Search
    ///
    /// `POST /locations/{locationId}/tasks/search`
    ///
    /// Requires scope: `locations/tasks.readonly`.
    pub async fn task_search_filter(
        &self,
        location_id: &str,
        body: &models::TaskSearchParamsDto,
    ) -> Result<models::LocationTaskListSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/tasks/search",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::POST, &path, &query, Some(body), Some("v3"))
            .await
    }

    /// GET all or email/sms templates
    ///
    /// `GET /locations/{locationId}/templates`
    ///
    /// Requires scope: `locations/templates.readonly`.
    pub async fn get_all_or_email_sms_templates(
        &self,
        location_id: &str,
        params: &GetAllOrEmailSmsTemplatesParams,
    ) -> Result<models::GetTemplatesSuccessfulResponseDto> {
        let path = format!(
            "/locations/{}/templates",
            crate::services::encode(location_id)
        );
        let query = params.to_query();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }

    /// DELETE an email/sms template
    ///
    /// `DELETE /locations/{locationId}/templates/{id}`
    pub async fn delete_an_email_sms_template(
        &self,
        location_id: &str,
        id: &str,
    ) -> Result<serde_json::Value> {
        let path = format!(
            "/locations/{}/templates/{}",
            crate::services::encode(location_id),
            crate::services::encode(id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(
                reqwest::Method::DELETE,
                &path,
                &query,
                None::<&()>,
                Some("v3"),
            )
            .await
    }

    /// Fetch Timezones
    ///
    /// Fetch the available timezones
    ///
    /// `GET /locations/{locationId}/timezones`
    ///
    /// Requires scope: `locations.readonly`.
    pub async fn fetch_timezones(&self, location_id: &str) -> Result<serde_json::Value> {
        let path = format!(
            "/locations/{}/timezones",
            crate::services::encode(location_id)
        );
        let query = Vec::new();
        self.client
            .send_versioned(reqwest::Method::GET, &path, &query, None::<&()>, Some("v3"))
            .await
    }
}
